// <auto-generated> Laubrary Zoetrope state names - do not edit. </auto-generated>
// Source: Assets/Demos/BarbarianDemo/Barbarian.asset  (GUID 56592c4a5e02bcf4398fb0de5ce78640)
// Rewritten every time that asset is saved. Rename a state in the Zoe window and this file
// follows it; the same name re-typed as a string literal in game code would not, and would
// fail silently at runtime instead of loudly at compile time.

namespace ZoeStates
{
    /// The states <c>Barbarian</c> declares, for asking it to show one by name.
    /// Hit and death are deliberately absent: they are fixed slots on the character, not names,
    /// so asking for them by name resolves to nothing.
    public static class BarbarianStates
    {
        /// Raised as <c>GutStab</c>.
        public const string GutStab = "GutStab";

        /// Raised as <c>HeavyChop</c>.
        public const string HeavyChop = "HeavyChop";

        /// Raised as <c>Dodge</c>.
        public const string Dodge = "Dodge";

        /// Raised as <c>JumpBack</c>.
        public const string JumpBack = "JumpBack";

        /// Raised as <c>Turnaround</c>.
        public const string Turnaround = "Turnaround";

        /// Raised as <c>PushedForwards</c>.
        public const string PushedForwards = "PushedForwards";

        /// Raised as <c>Headbutt</c>.
        public const string Headbutt = "Headbutt";

        /// Raised as <c>PushedBackwards</c>.
        public const string PushedBackwards = "PushedBackwards";

        /// Raised as <c>GutStabLong</c>.
        public const string GutStabLong = "GutStabLong";

        /// Raised as <c>HeadChop</c>.
        public const string HeadChop = "HeadChop";

        /// Raised as <c>NeckSlice</c>.
        public const string NeckSlice = "NeckSlice";

        /// Raised as <c>OverCleave</c>.
        public const string OverCleave = "OverCleave";

        /// Raised as <c>Hit</c>.
        public const string Hit = "Hit";

        /// Raised as <c>PushKick</c>.
        public const string PushKick = "PushKick";

        /// Raised as <c>Roll</c>.
        public const string Roll = "Roll";

        /// Raised as <c>SwordCyclone</c>.
        public const string SwordCyclone = "SwordCyclone";

        /// Every state name above, in the order the character declares them.
        public static readonly string[] All = { "GutStab", "HeavyChop", "Dodge", "JumpBack", "Turnaround", "PushedForwards", "Headbutt", "PushedBackwards", "GutStabLong", "HeadChop", "NeckSlice", "OverCleave", "Hit", "PushKick", "Roll", "SwordCyclone" };
    }
}
