using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Unity.Collections;
using Unity.Mathematics;
using UnityEngine;
using Laubrary.ZTracker.Model;

namespace Laubrary.ZTracker.Engine
{
    // Direct reflection/eval entry point; no Test Runner, authoring changes or menu.
    public static class TrackerP4Check
    {
        public static Mapping Route(string name,float min,float max,string units="legacy parameter units")=>new Mapping{min=min,max=max,target=new ParameterTarget{kind=ParameterKind.Synth,parameter=name,units=units}};
        public static ZTrackerInstrument Synth(bool fm=false)
        {
            var a=ScriptableObject.CreateInstance<ZTrackerInstrument>();a.type=fm?InstrumentType.FM:InstrumentType.Synth;a.attack=0;a.decay=0;a.sustain=1;a.release=.02f;a.volume=.2f;
            if(!ZTrackerMigration.Upgrade(a,out string error))throw new Exception(error);a.model.modulation.Clear();return a;
        }
        static void Need(bool ok,string message){if(!ok)throw new Exception(message);}
        static float Live(TrackerOffline e,TrackerParameter p)=>e.Snapshot.parameterLive[(int)p];
        public static string Execute()
        {
            int pass=0,fail=0;var report=new StringBuilder();Action<string,Action> check=(name,run)=>{try{run();pass++;report.AppendLine("PASS "+name);}catch(Exception ex){fail++;report.AppendLine("FAIL "+name+": "+ex.Message);}};
            var clip=AudioClip.Create("P4 probe",48000,1,48000,false);var raw=new float[48000];for(int n=0;n<raw.Length;n++)raw[n]=.2f*(float)Math.Sin(n*.07);clip.SetData(raw,0);
            var sample=TrackerEngineCheck.FixtureInstrument(clip);var synth=Synth();var fm=Synth(true);var all=new[]{sample,synth,fm};
            using(var l=new NativeArray<float>(32768,Allocator.Persistent))using(var r=new NativeArray<float>(32768,Allocator.Persistent))try{
                foreach(var instrument in all){string label=instrument==sample?"sampler":instrument==fm?"FM":"synth";
                    check(label+" all eight defaults/set/clamping and authored immutability",()=>{for(int n=0;n<8;n++){instrument.model.macros[n].value=n/8f;instrument.model.macros[n].mappings.Add(Route("pan",-1,1));}string before=ZTrackerMigration.Json(instrument.model);using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(TrackerEngineCheck.FixtureSong(instrument)))){e.SendCommand(TrackerCommand.Audition(0,69));e.Render(l,r,64);for(int n=0;n<8;n++){Need(e.ObserveMacro(0,n)==n/8f,"default "+n);e.SetMacro(0,n,.37f);Need(e.ObserveMacro(0,n)==.37f,"set "+n);}e.SetMacro(0,7,2);Need(Live(e,TrackerParameter.Pan)==1,"normalized clamp");Need(e.Compiled,"not Burst");}Need(before==ZTrackerMigration.Json(instrument.model),"mutated authored defaults");foreach(var m in instrument.model.macros){m.value=0;m.mappings.Clear();}});
                    check(label+" active-only slew, exact explicit tick, background/released excluded",()=>{using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(TrackerEngineCheck.FixtureSong(instrument)))){e.TargetMacro(0,7,1,.2f);e.SendCommand(new TrackerCommand{kind=TrackerCommandKind.MacroAdvance,a=0});Need(e.ObserveMacro(0,7)==0,"inactive slid");e.SendCommand(TrackerCommand.Audition(0,69));e.Render(l,r,64);for(int n=0;n<5;n++)e.SendCommand(new TrackerCommand{kind=TrackerCommandKind.MacroAdvance,a=0});Need(e.ObserveMacro(0,7)==1,"target not reached");e.TargetMacro(0,7,0,.1f);e.SendCommand(new TrackerCommand{kind=TrackerCommandKind.AuditionOff});e.SendCommand(new TrackerCommand{kind=TrackerCommandKind.MacroAdvance,a=0});Need(e.ObserveMacro(0,7)==1,"released slid");}});
                    check(label+" direct then macro index/list last write, reversed/constant/curve routes",()=>{var m=instrument.model.macros;m[0].mappings.Add(Route("pan",1,-1));m[0].value=.25f;m[1].mappings.Add(Route("pan",.2f,.2f));m[1].mappings.Add(Route("pan",-.4f,.8f));m[1].value=.5f;m[7].value=.5f;var curve=Route("volume",0,1);curve.curvePoints.Add(new ModulationPoint{time=0,value=0});curve.curvePoints.Add(new ModulationPoint{time=.5,value=.25f});curve.curvePoints.Add(new ModulationPoint{time=1,value=1});m[7].mappings.Add(curve);using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(TrackerEngineCheck.FixtureSong(instrument)))){e.SendCommand(TrackerCommand.SetParameter(0,TrackerParameter.Pan,-1));e.SendCommand(TrackerCommand.Audition(0,69));e.Render(l,r,64);Need(Math.Abs(Live(e,TrackerParameter.Pan)-.2f)<1e-6,"order conflict");Need(Live(e,TrackerParameter.Volume)==.25f,"explicit curve");}foreach(var macro in m){macro.value=0;macro.mappings.Clear();}});
                }
                check("valid route survives unsupported neighbor; physical units not guessed",()=>{synth.model.macros[0].mappings.Add(Route("vibratoRate",2,10,"Hz"));synth.model.macros[0].value=.25f;synth.model.macros[1].mappings.Add(Route("vibratoRate",100,200,"seconds"));synth.model.macros[2].mappings.Add(new Mapping{target=new ParameterTarget{unresolved=true,parameter="unknown"}});using(var p=TrackerPreparedSong.Prepare(TrackerEngineCheck.FixtureSong(synth))){Need(p.macroRouteCount==1&&p.diagnostics.Any(d=>d.Contains("UNITS_UNSUPPORTED"))&&p.diagnostics.Any(d=>d.Contains("UNRESOLVED")),"valid route lost");using(var e=new TrackerOffline(p)){e.SendCommand(TrackerCommand.Audition(0,69));e.Render(l,r,64);Need(Live(e,TrackerParameter.VibratoRate)==4,"Hz units");}}foreach(var m in synth.model.macros){m.value=0;m.mappings.Clear();}});
                check("typed target kind and family applicability; legacy common sampler controls retained",()=>{sample.model.macros[0].mappings.Add(Route("pan",0,1,"normalized"));sample.model.macros[1].mappings.Add(Route("fmOperators.0.level",0,1));var typed=Route("volume",0,1,"normalized");typed.target.kind=ParameterKind.Sample;sample.model.macros[2].mappings.Add(typed);sample.model.macros[3].mappings.Add(Route("pan",-1,1));using(var p=TrackerPreparedSong.Prepare(TrackerEngineCheck.FixtureSong(sample)))Need(p.macroRouteCount==2&&p.diagnostics.Count(d=>d.Contains("FAMILY_UNSUPPORTED"))==2,"family accepted/valid links lost");foreach(var m in sample.model.macros)m.mappings.Clear();synth.model.macros[0].mappings.Add(Route("fmOperators.0.level",0,1));typed=Route("volume",0,1);typed.target.kind=ParameterKind.Sample;synth.model.macros[1].mappings.Add(typed);using(var p=TrackerPreparedSong.Prepare(TrackerEngineCheck.FixtureSong(synth)))Need(p.macroRouteCount==0,"wrong target family");foreach(var m in synth.model.macros)m.mappings.Clear();});
                check("saved vs native wave and envelope enums preserve originals",()=>{foreach(var domain in new[]{SoundEnumDomain.SavedAuthoring,SoundEnumDomain.NativeDirect}){int[] expected=domain==SoundEnumDomain.SavedAuthoring?new[]{0,4,2,1,5}:new[]{0,1,2,3,4};for(int n=0;n<5;n++){synth.model.parameters.enumDomain=domain;synth.model.parameters.waveA=n;using(var p=TrackerPreparedSong.Prepare(TrackerEngineCheck.FixtureSong(synth)))Need(p.state.tones[0].waveA==expected[n]&&synth.model.parameters.waveA==n,"wave mapping "+domain+" "+n);}}synth.model.parameters.waveA=0;synth.model.parameters.enumDomain=SoundEnumDomain.SavedAuthoring;foreach(int mode in new[]{1,2}){var env=new ZUIEnvelopeData{enabled=true,requiresEndPoint=false,loopEnabled=true,loopMode=mode,loopStart=0,loopEnd=.02f};env.points.Add(new ZUIEnvelopePoint(0,0));env.points.Add(new ZUIEnvelopePoint(.02f,1));synth.model.parameters.blendEnvelopeData=env;using(var p=TrackerPreparedSong.Prepare(TrackerEngineCheck.FixtureSong(synth)))Need(p.state.toneEnvelopes[0].loop==(mode==1?SampleLoop.Forward:SampleLoop.PingPong)&&env.loopMode==mode,"loop provenance");}synth.model.parameters.blendEnvelopeData=null;});
                check("FM6/7 compile to named existing parallel fallback without mutation",()=>{foreach(int algorithm in new[]{6,7}){fm.model.parameters.fmAlgorithm=algorithm;using(var p=TrackerPreparedSong.Prepare(TrackerEngineCheck.FixtureSong(fm)))Need(p.state.tones[0].algorithm==5&&p.diagnostics.Any(d=>d.Contains("FALLBACK"))&&fm.model.parameters.fmAlgorithm==algorithm,"fallback");}fm.model.parameters.fmAlgorithm=0;});
                check("external slot -> declared ID -> linked instrument, macro/direct precedence",()=>{var song=TrackerEngineCheck.FixtureSong(synth);song.instruments.Add(fm);synth.model.id="lead";fm.model.id="linked";song.tracks[0].externalSources.Add(new ExternalSourceDevice{id="source",pluginId="plugin",instrumentId="linked",parameterNumbers=new List<string>{"88","3"}});fm.model.externalParameters.Add(new ExternalParameterMapping{externalId="88",mapping=Route("fmFeedback",0,2)});fm.model.externalParameters.Add(new ExternalParameterMapping{externalId="3",mapping=new Mapping{min=0,max=1,target=new ParameterTarget{kind=ParameterKind.InstrumentMacro,index=7,parameter="macro",units="normalized"}}});fm.model.macros[7].mappings.Add(Route("volume",0,1));using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){Need(e.SetExternal("notes","source",0,.75f),"slot resolution");Need(e.Snapshot.parameterLive[TrackerParameters.Stride+(int)TrackerParameter.FMFeedback]==1.5f,"used ordinal/name");Need(e.SetExternal("notes","source",1,.4f)&&e.ObserveMacro(1,7)==.4f,"external macro");Need(!e.SetExternal("notes","plugin",0,1)&&!e.SetExternal("notes","source",88,1),"guessed identity");}fm.model.externalParameters.Clear();fm.model.macros[7].mappings.Clear();});
                check("sample local volume/pan preserved at zero instrument gain",()=>{sample.model.sampler.volume=0;sample.model.sampler.samples[0].volume=.25f;sample.model.sampler.samples[0].pan=.5f;using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(TrackerEngineCheck.FixtureSong(sample)))){e.SendCommand(TrackerCommand.SetParameter(0,TrackerParameter.Volume,.8f));e.SendCommand(TrackerCommand.SetParameter(0,TrackerParameter.Pan,-.25f));e.SendCommand(TrackerCommand.Audition(0,69));e.Render(l,r,64);Need(e.Snapshot.tones[0].localVolume==.25f&&e.Snapshot.tones[0].localPan==.5f&&e.Snapshot.voices[0].amplitude>0,"sample globals overwrote local values");}sample.model.sampler.volume=1;sample.model.sampler.samples[0].volume=1;sample.model.sampler.samples[0].pan=0;});
                check("macro fine tuning before note applied once and release captures live seconds",()=>{synth.model.macros[0].mappings.Add(Route("fineTune",1200,1200,"cents"));synth.model.macros[1].mappings.Add(Route("release",.1f,.1f,"seconds"));using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(TrackerEngineCheck.FixtureSong(synth)))){e.SendCommand(TrackerCommand.Audition(0,69));e.Render(l,r,64);Need(Math.Abs(e.Snapshot.voices[0].phaseA-(64*880d/48000)%1)<1e-5,"fine tuning doubled");e.SendCommand(new TrackerCommand{kind=TrackerCommandKind.AuditionOff});Need(Math.Abs(e.Snapshot.voices[0].releaseStep-1f/4800)<1e-7,"release ignored macro");}synth.model.macros[0].mappings.Clear();synth.model.macros[1].mappings.Clear();});
                check("independent B loops/cursors and authored extension defaults",()=>{var a=sample.model.sampler.samples[0];a.loop=SampleLoop.Forward;a.loopStartFrame=7;a.loopEndFrame=23;foreach(var loop in new[]{SampleLoop.Forward,SampleLoop.Backward,SampleLoop.PingPong}){sample.model.sampler.zones[0].blend=new SampleBlendExtension{pcmB=clip,baseNoteB=64,amount=.8f,pmDepth=17,loopB=loop,loopStartFrameB=31,loopEndFrameB=53};using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(TrackerEngineCheck.FixtureSong(sample)))){e.SendCommand(TrackerCommand.Audition(0,69));e.Render(l,r,1000,333);var v=e.Snapshot.voices[0];Need(v.position>=7&&v.position<23&&v.positionB>=31&&v.positionB<53&&v.step!=v.stepB,"B cursor shared "+loop);Need(v.blendCurrent==.8f,"zone blend default overwritten");}}sample.model.sampler.zones[0].blend=null;a.loop=SampleLoop.Off;});
                check("cohort release/stealing generation guard and reused state",()=>{synth.model.parameters.unisonVoices=3;var song=TrackerEngineCheck.FixtureSong(synth);song.voiceCapacity=3;using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Audition(0,69));e.Render(l,r,64);long old=e.Snapshot.voices[0].cohort;e.SendCommand(TrackerCommand.ReleaseVoice(1,old));Need(e.Snapshot.voices.ToArray().All(v=>v.released),"partial unison release");e.SendCommand(TrackerCommand.Audition(0,72));e.Render(l,r,64);e.SendCommand(TrackerCommand.ReleaseVoice(1,old));Need(e.Snapshot.voices.ToArray().All(v=>v.active&&!v.released&&v.note==72&&v.cohort!=old),"stale release/partial stealing");Need(e.Snapshot.voices.ToArray().All(v=>v.fmPrevious==0&&v.positionB==0),"reused state");}synth.model.parameters.unisonVoices=1;});
                foreach(int wave in new[]{4,5})check((wave==4?"white":"pink")+" seeded repeatability/partition/independent voices/spectral slope",()=>{synth.model.parameters.enumDomain=SoundEnumDomain.NativeDirect;synth.model.parameters.waveA=wave==4?5:6;synth.model.parameters.blend=0;float[] baseline=null;foreach(int block in new[]{64,333,1024}){using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(TrackerEngineCheck.FixtureSong(synth)))){e.SendCommand(TrackerCommand.Audition(0,69));e.Render(l,r,32768,block);var data=l.ToArray();Need(data.All(math.isfinite)&&data.Max(Math.Abs)>.01f,"noise silent/nonfinite");if(baseline==null)baseline=data;else Need(baseline.SequenceEqual(data),"partition/seed changed");}}double low=0,high=0;foreach(int bin in new[]{64,96,128,192,4096,6144,8192,12288}){double re=0,im=0;for(int n=0;n<baseline.Length;n++){double window=.5-.5*Math.Cos(n*Math.PI*2/(baseline.Length-1));re+=baseline[n]*window*Math.Cos(2*Math.PI*bin*n/baseline.Length);im+=baseline[n]*window*Math.Sin(2*Math.PI*bin*n/baseline.Length);}if(bin<256)low+=re*re+im*im;else high+=re*re+im*im;}double ratio=low/high;report.AppendLine("MEASURE noiseLowHigh="+ratio);Need(wave==4?ratio>.05&&ratio<20:ratio>8,"spectral slope "+ratio);synth.model.parameters.enumDomain=SoundEnumDomain.SavedAuthoring;synth.model.parameters.waveA=0;});
                check("P4 FM/B/unison/macros render without scoped allocations",()=>{var song=TrackerEngineCheck.FixtureSong(sample,3);song.voiceCapacity=16;song.instruments.Add(synth);song.instruments.Add(fm);synth.model.parameters.unisonVoices=3;sample.model.sampler.zones[0].blend=new SampleBlendExtension{pcmB=clip,amount=.4f};var a=TrackerEngineCheck.Note(69,0);var b=TrackerEngineCheck.Note(69,1);b.instrument=1;var c=TrackerEngineCheck.Note(69,2);c.instrument=2;song.patterns[0].tracks[0].WriteLine(new PatternLine{line=0,notes=new List<NoteCell>{a,b,c}});foreach(var ins in all)ins.model.macros[7].mappings.Add(Route("volume",.1f,.3f));using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,1024);long before=GC.GetAllocatedBytesForCurrentThread();for(int n=0;n<32;n++){e.SetMacro(0,7,n/32f);e.SetMacro(1,7,n/32f);e.SetMacro(2,7,n/32f);e.Render(l,r,333,333);}long bytes=GC.GetAllocatedBytesForCurrentThread()-before;Need(bytes==0&&e.Compiled,"allocated/managed "+bytes);report.AppendLine("MEASURE p4RenderAllocatedBytes="+bytes);}foreach(var ins in all)ins.model.macros[7].mappings.Clear();synth.model.parameters.unisonVoices=1;sample.model.sampler.zones[0].blend=null;});
            }finally{foreach(var ins in all)UnityEngine.Object.DestroyImmediate(ins);UnityEngine.Object.DestroyImmediate(clip);}
            return "TrackerP4Check "+pass+" passed / "+fail+" failed\n"+report;
        }
    }
}
