using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Laubrary.Audio;
using Laubrary.ZTracker.Model;
using Unity.Collections;
using UnityEngine;

namespace Laubrary.ZTracker.Engine
{
    /// <summary>Reusable internal engine checks. No menu, Test Runner, asset writes, legacy playback or audio device takeover.</summary>
    public static class TrackerEngineCheck
    {
        public static SongData FixtureSong(ZTrackerInstrument instrument,int columns=1,int lines=8,double bpm=120)
        {
            var s=new SongData{id="check-song",bpm=bpm,voiceCapacity=8,beatTicks=false};s.instruments.Add(instrument);
            s.tracks.Add(new TrackData{id="notes",visibleNoteColumns=columns,visibleEffectColumns=1});s.tracks.Add(new TrackData{id="master",kind=TrackKind.Master,visibleNoteColumns=0});
            var p=new PatternData{id="pattern",lineCount=lines};p.tracks.Add(new PatternTrack{trackId="notes"});p.tracks.Add(new PatternTrack{trackId="master"});s.patterns.Add(p);s.sequence.Add(new SequenceSlot{id="slot",patternId="pattern"});return s;
        }
        public static ZTrackerInstrument FixtureInstrument(AudioClip clip)
        {
            var a=ScriptableObject.CreateInstance<ZTrackerInstrument>();a.sampleClip=clip;a.attack=0;a.decay=0;a.sustain=1;a.release=1;
            if(!ZTrackerMigration.Upgrade(a,out string error)){UnityEngine.Object.DestroyImmediate(a);throw new Exception(error);}return a;
        }
        public static NoteCell Note(int note=60,int column=0,int volume=128)=>new NoteCell{column=column,note=NoteKind.Note,pitch=note,instrumentPresent=true,instrument=0,volume=new ColumnValue{kind=ValueKind.Value,value=volume}};
        static void Line(SongData s,int row,params NoteCell[] cells){s.patterns[0].tracks[0].WriteLine(new PatternLine{line=row,notes=new List<NoteCell>(cells)});}
        public static string Execute()
        {
            var report=new StringBuilder();int pass=0,fail=0;
            Action<string,Action> check=(name,run)=>{try{run();pass++;report.AppendLine("PASS "+name);}catch(Exception ex){fail++;report.AppendLine("FAIL "+name+": "+ex.Message);}};
            Action<bool,string> need=(condition,message)=>{if(!condition)throw new Exception(message);};
            var clip=AudioClip.Create("tracker-check",48000,1,48000,false);var raw=new float[48000];for(int i=0;i<raw.Length;i++)raw[i]=.1f;clip.SetData(raw,0);var instrument=FixtureInstrument(clip);
            var l=new NativeArray<float>(48000,Allocator.Persistent);var r=new NativeArray<float>(48000,Allocator.Persistent);
            try {
                check("schema1 only, no authored mutation, shared PCM",()=>{var s=FixtureSong(instrument);s.instruments.Add(instrument);Line(s,0,Note());string before=ZTrackerMigration.Json(instrument.model);using(var p=TrackerPreparedSong.Prepare(s)){need(p.PcmCount==1,"Duplicate PCM copied");}need(before==ZTrackerMigration.Json(instrument.model),"Preparation mutated instrument");var old=ScriptableObject.CreateInstance<ZTrackerSong>();try{bool refused=false;try{TrackerPreparedSong.Prepare(old);}catch(ArgumentException){refused=true;}need(refused,"Schema0 accepted");}finally{UnityEngine.Object.DestroyImmediate(old);}});
                check("actual Burst witness, native guard, active output, scoped zero render allocation",()=>{var s=FixtureSong(instrument);Line(s,0,Note());using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(s))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,4096);need(e.Compiled,"Job ran managed");long managed=AudioThreadGuard.ManagedBlocks;long blocks=AudioThreadGuard.Blocks;for(int i=0;i<4;i++)e.Render(l,r,4096);long before=GC.GetAllocatedBytesForCurrentThread();for(int i=0;i<20;i++)e.Render(l,r,1024);long allocated=GC.GetAllocatedBytesForCurrentThread()-before;need(allocated==0,"Allocated "+allocated);need(AudioThreadGuard.ManagedBlocks==managed,"Managed render blocks");need(AudioThreadGuard.Blocks>blocks,"No measured native blocks");need(Math.Abs(l[0])>.001,"Silent render");report.AppendLine("MEASURE renderAllocatedBytes="+allocated+" nativeBlocks="+(AudioThreadGuard.Blocks-blocks)+" managedBlocksDelta="+(AudioThreadGuard.ManagedBlocks-managed));}});
                check("fractional clock exact frames across 64/333/1024 partitions",()=>{long[] expected={0,5236,10472,15709,20945,26181};foreach(int size in new[]{64,333,1024}){var s=FixtureSong(instrument,bpm:137.5);using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(s))){e.SendCommand(TrackerCommand.Play(false));e.Render(l,r,32000,size);var rows=new List<long>();while(e.ReadEvent(out var ev))if(ev.kind==TrackerEventKind.Row)rows.Add(ev.samplePosition);need(rows.Take(6).SequenceEqual(expected),"Clock "+size+": "+string.Join(",",rows.Take(6)));}}});
                check("first row before first sample, exact fractional delay, numeric zero silence",()=>{var s=FixtureSong(instrument);var n=Note();n.delayPresent=true;n.delay=128;Line(s,0,n);using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(s))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,4000,333);need(l[2999]==0&&Math.Abs(l[3000])>.001,"Delay not frame3000");var onset=new List<long>();while(e.ReadEvent(out var ev))if(ev.kind==TrackerEventKind.NoteOn)onset.Add(ev.samplePosition);need(onset.SequenceEqual(new long[]{3000}),"Delayed note event");}s=FixtureSong(instrument);Line(s,0,Note(volume:0));using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(s))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,200);need(l.ToArray().Take(200).All(x=>x==0),"Literal volume0 became empty");}});
                check("column instrument memory, OFF ownership and simultaneous layers",()=>{var s=FixtureSong(instrument,2);instrument.model.sampler.zones.Add(ZTrackerMigration.Copy(instrument.model.sampler.zones[0]));try{Line(s,0,Note(column:0),Note(column:1));Line(s,1,new NoteCell{column=0,note=NoteKind.Off});using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(s))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,6100);var voices=e.Snapshot.voices.ToArray().Where(v=>v.active).ToArray();need(voices.Length==4,"Layer count");need(voices.Count(v=>v.column==0&&v.released)==2&&voices.Count(v=>v.column==1&&!v.released)==2,"OFF affected another column");}}finally{instrument.model.sampler.zones.RemoveAt(1);}});
                check("inclusive note/velocity boundaries and fixed pitch",()=>{var z=instrument.model.sampler.zones[0];bool old=z.keyTracking;z.keyTracking=false;z.noteMin=30;z.noteMax=90;z.velocityMin=40;z.velocityMax=90;try{foreach(int vel in new[]{39,40,90,91}){using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(FixtureSong(instrument)))){e.SendCommand(TrackerCommand.Audition(0,30,vel));e.Render(l,r,20);need(e.Snapshot.voices.ToArray().Count(v=>v.active)==(vel>=40&&vel<=90?1:0),"Velocity boundary "+vel);if(vel==40)need(e.Snapshot.voices[0].step==1,"Fixed pitch transposed");}}}finally{z.keyTracking=old;z.noteMin=0;z.noteMax=119;z.velocityMin=0;z.velocityMax=127;}});
                check("Forward, Backward, PingPong and release exit loops",()=>{var sample=instrument.model.sampler.samples[0];try{foreach(var loop in new[]{SampleLoop.Forward,SampleLoop.Backward,SampleLoop.PingPong}){sample.loop=loop;sample.loopStartFrame=2;sample.loopEndFrame=8;sample.releaseExitsLoop=false;using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(FixtureSong(instrument)))){e.SendCommand(TrackerCommand.Audition(0,60));e.Render(l,r,31);var v=e.Snapshot.voices[0];need(v.active&&v.position>=2&&v.position<8,"Loop escaped "+loop+": "+v.position);}}sample.loop=SampleLoop.Forward;sample.releaseExitsLoop=true;using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(FixtureSong(instrument)))){e.SendCommand(TrackerCommand.Audition(0,60));e.Render(l,r,20);e.SendCommand(new TrackerCommand{kind=TrackerCommandKind.AuditionOff,a=0,b=0});e.Render(l,r,20);need(e.Snapshot.voices[0].position>8&&e.Snapshot.voices[0].released,"Release did not exit loop");}}finally{sample.loop=SampleLoop.Off;sample.releaseExitsLoop=false;}});
                check("AHDSR hold, sustain and frozen release slope",()=>{var env=instrument.model.modulation[0].devices[0];float oldHold=env.hold;env.hold=.01f;env.decay=.01f;env.sustain=.5f;try{using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(FixtureSong(instrument)))){e.SendCommand(TrackerCommand.Audition(0,60));e.Render(l,r,100);need(e.Snapshot.voices[0].envelope==1,"Hold skipped");e.Render(l,r,1000);need(Math.Abs(e.Snapshot.voices[0].envelope-.5)<1e-6,"Sustain incorrect");e.SendCommand(new TrackerCommand{kind=TrackerCommandKind.AuditionOff});e.Render(l,r,1000);need(Math.Abs(e.Snapshot.voices[0].envelope-(.5-1000*.5/48000))<5e-5,"Release not frozen linear");}}finally{env.hold=oldHold;env.decay=0;env.sustain=1;}});
                check("bounded voice stealing and reused filter history reset",()=>{var s=FixtureSong(instrument);s.voiceCapacity=1;instrument.model.parameters.instFilterEnabled=true;instrument.model.parameters.instFilterCutoff=.1f;try{using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(s))){e.SendCommand(TrackerCommand.Audition(0,60));e.Render(l,r,1000);e.SendCommand(TrackerCommand.Audition(0,72));e.Render(l,r,64);float[] reused=l.ToArray().Take(64).ToArray();using(var fresh=new TrackerOffline(TrackerPreparedSong.Prepare(s))){fresh.SendCommand(TrackerCommand.Audition(0,72));fresh.Render(l,r,64);need(reused.Zip(l.ToArray().Take(64),(a,b)=>Math.Abs(a-b)).Max()<1e-6,"Filter history leaked");}need(e.Snapshot.voices.Length==1,"Unbounded voice allocation");need(e.Snapshot.voices[0].note==72,"Wrong steal target");bool stolen=false;while(e.ReadEvent(out var ev))stolen|=ev.kind==TrackerEventKind.VoiceStolen;need(stolen,"No steal event");}}finally{instrument.model.parameters.instFilterEnabled=false;}});
                check("group graph, insertion send taps, pre/post fader, output mute tails",()=>{var s=FixtureSong(instrument);s.tracks.Insert(1,new TrackData{id="send",kind=TrackKind.Send,visibleNoteColumns=0});s.tracks.Insert(1,new TrackData{id="group",kind=TrackKind.Group,visibleNoteColumns=0});s.patterns[0].tracks.Add(new PatternTrack{trackId="send"});s.patterns[0].tracks.Add(new PatternTrack{trackId="group"});s.tracks[0].parentGroupId="group";s.tracks[0].postVolume=.5f;s.tracks[0].devices.nodes.Add(new AudioEffectNodeData{type=Laubrary.Zounds.ZoundEffectType.Gain,p=new[]{2f}});s.tracks[0].sends.Add(new SendDestination{trackId="send",devicePosition=1,gain=.25f,postfader=false});Line(s,0,Note());using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(s))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,64);need(Math.Abs(l[2]-.1f*Math.Sqrt(.5)*1.5)<1e-6,"Insertion send/group sum incorrect: "+l[2]);e.SendCommand(new TrackerCommand{kind=TrackerCommandKind.TrackMute,a=0,b=1});e.Render(l,r,64);need(l[2]==0,"Muted output still sent");}});
                check("per-track instrument FX attribution",()=>{var s=FixtureSong(instrument);s.tracks.Insert(1,new TrackData{id="second",postVolume=.25f});s.patterns[0].tracks.Add(new PatternTrack{trackId="second"});instrument.model.fxChains.Add(new AudioEffectChainData{nodes=new List<AudioEffectNodeData>{new AudioEffectNodeData{type=Laubrary.Zounds.ZoundEffectType.Gain,p=new[]{2f}}}});instrument.model.sampler.samples[0].fxChain=0;try{Line(s,0,Note());s.patterns[0].tracks.Find(t=>t.trackId=="second").WriteLine(new PatternLine{line=0,notes=new List<NoteCell>{Note()}});using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(s))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,64);need(e.Snapshot.busCount==2,"Instrument FX merged tracks");need(Math.Abs(l[63]-.125)<1e-5,"Per-track FX attribution incorrect: "+l[63]);}}finally{instrument.model.fxChains.Clear();instrument.model.sampler.samples[0].fxChain=-1;}});
                check("unsupported commands diagnosed and ignored; synth silence",()=>{var s=FixtureSong(instrument);Line(s,0,Note());s.patterns[0].tracks[0].lines[0].effects.Add(new EffectCell{command=new CommandData{present=true,valuePresent=true,identifier="0S",value=255}});using(var p=TrackerPreparedSong.Prepare(s))need(p.diagnostics.Any(d=>d.Contains("P5_COMMAND_IGNORED")),"Unsupported command lost diagnostic");var family=instrument.model.family;instrument.model.family=InstrumentFamily.Synth;try{using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(s))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,64);need(l[1]==0,"Synth reached old DLL");}}finally{instrument.model.family=family;}});
                check("event ring bounded overflow and FIFO publication",()=>{var ring=TrackerEventRing.Create(2);try{ring.Write(new TrackerEvent{samplePosition=10});ring.Write(new TrackerEvent{samplePosition=20});ring.Write(new TrackerEvent{samplePosition=30});need(ring.OverflowCount==1,"Overflow not counted");need(ring.TryRead(out var a)&&a.samplePosition==10&&ring.TryRead(out var b)&&b.samplePosition==20&&!ring.TryRead(out _),"FIFO incorrect");}finally{ring.Dispose();}});
                check("cycles and malformed layouts refused before publication",()=>{var s=FixtureSong(instrument);s.tracks[0].outputTrackId="notes";bool rejected=false;try{TrackerPreparedSong.Prepare(s);}catch(ArgumentException){rejected=true;}need(rejected,"Cycle accepted");s=FixtureSong(instrument);s.tracks[0].devices.nodes.Add(new AudioEffectNodeData{type=(Laubrary.Zounds.ZoundEffectType)999});rejected=false;try{TrackerPreparedSong.Prepare(s);}catch(ArgumentException){rejected=true;}need(rejected,"Unknown effect accepted");});
            }
            finally{l.Dispose();r.Dispose();UnityEngine.Object.DestroyImmediate(instrument);UnityEngine.Object.DestroyImmediate(clip);}
            return "TrackerEngineCheck "+pass+" passed / "+fail+" failed\n"+report;
        }
    }
}
