using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Laubrary.Audio;
using Laubrary.ZTracker.Model;
using Laubrary.Zounds;
using Laubrary.Zounds.Dsp;
using Unity.Collections;
using UnityEngine;

namespace Laubrary.ZTracker.Engine
{
    public static partial class TrackerEngineCheck
    {
        static void Command(SongData song,int row,string identifier,int value,int column=0)
        {
            var track=song.patterns[0].tracks[0];var line=track.lines.Find(x=>x.line==row)??new PatternLine{line=row};
            line.effects.Add(new EffectCell{column=column,command=new CommandData{present=true,valuePresent=true,identifier=identifier,value=value}});track.WriteLine(line);
        }
        static List<TrackerEvent> Events(TrackerOffline engine){var events=new List<TrackerEvent>();while(engine.ReadEvent(out var e))events.Add(e);return events;}
        static unsafe void Advanced(Action<string,Action> check,Action<bool,string> need,ZTrackerInstrument instrument,NativeArray<float> l,NativeArray<float> r,StringBuilder report)
        {
            check("six clock traces follow independent Kahan/Q policy and partition invariance",()=>{
                foreach(var setting in new[]{(120d,4,6),(137.5d,4,6),(73.25d,7,5),(255d,16,16),(32d,3,1),(999d,256,8)}){
                    var song=FixtureSong(instrument,lines:8,bpm:setting.Item1);song.linesPerBeat=setting.Item2;song.ticksPerLine=setting.Item3;
                    double sum=0,compensation=0;var expected=new List<long>();for(int row=0;row<8;row++){double nearest=Math.Round(sum);long bits=BitConverter.DoubleToInt64Bits(Math.Max(1,Math.Abs(sum)));int exponent=(int)((bits>>52)&2047)-1023;double ulp=Math.Pow(2,exponent-52);expected.Add((long)(Math.Abs(sum-nearest)<=8*ulp?nearest:Math.Floor(sum)));double y=48000*60d/(setting.Item1*setting.Item2)-compensation,next=sum+y;compensation=(next-sum)-y;sum=next;}
                    int frames=(int)Math.Min(48000,sum+1);foreach(int block in new[]{64,333,1024})using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play(false));e.Render(l,r,frames,block);var actual=Events(e).Where(x=>x.kind==TrackerEventKind.Row).Select(x=>x.samplePosition).ToList();need(actual.SequenceEqual(expected.Where(x=>x<frames)),"Clock trace mismatch "+setting+" / "+block);}
                }
            });
            check("ZT/ZL/ZK apply once at row entry, ZB raw row and clamps",()=>{
                var song=FixtureSong(instrument,lines:8);song.tracks[0].visibleEffectColumns=4;Command(song,0,"ZT",240);Command(song,0,"ZL",2,1);Command(song,0,"ZK",4,2);Command(song,0,"ZB",3,3);var second=ZTrackerMigration.Copy(song.patterns[0]);second.id="second";second.tracks[0].lines.Clear();song.patterns.Add(second);song.sequence.Add(new SequenceSlot{id="next",patternId="second"});
                using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play(false));e.Render(l,r,6100,333);var events=Events(e);need(events.Any(x=>x.kind==TrackerEventKind.Row&&x.samplePosition==6000&&x.sequence==1&&x.row==3),"Break boundary");need(events.Where(x=>x.kind==TrackerEventKind.Tick&&x.sequence==0).Select(x=>x.samplePosition).SequenceEqual(new long[]{0,1500,3000,4500}),"Tick count/duration");}
                song.patterns[0].tracks[0].lines[0].effects.Last().command.value=255;using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play(false));e.Render(l,r,6100);var events=Events(e);need(events.Any(x=>x.kind==TrackerEventKind.Row&&x.sequence==1&&x.row==7),"Break clamp");need(events.Any(x=>x.kind==TrackerEventKind.Diagnostic&&x.payload==(int)TrackerRuntimeDiagnostic.BreakClamped),"Break clamp not diagnosed");}
            });
            check("ZT00/ZL00 stop cuts audio; disputed BPM retained with diagnostic",()=>{
                foreach(string id in new[]{"ZT","ZL"}){var song=FixtureSong(instrument);Line(song,0,Note());Command(song,1,id,0);using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,6500);need(l[5999]!=0&&l[6000]==0&&!e.Snapshot.playing,"Global stop kept audio "+id);}}
                var disputed=FixtureSong(instrument);Command(disputed,0,"ZT",24);using(var p=TrackerPreparedSong.Prepare(disputed))need(p.diagnostics.Any(x=>x.Contains("BPM_RANGE_DISPUTE")),"Disputed BPM changed timing");
            });
            check("transport idle counter, fresh restart resets timing and mixer",()=>{
                var song=FixtureSong(instrument);Line(song,0,Note());Command(song,1,"ZT",240);using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,7000);long count=e.Snapshot.samplePosition;need(e.Snapshot.bpm==240,"Tempo not changed");e.SendCommand(TrackerCommand.Stop());e.Render(l,r,512);need(e.Snapshot.samplePosition==count&&l[0]==0,"Idle advanced transport or rang tail");e.SendCommand(new TrackerCommand{kind=TrackerCommandKind.TrackGain,a=0,value=.25f});e.SendCommand(TrackerCommand.Play());e.Render(l,r,10);need(e.Snapshot.bpm==120&&e.Snapshot.tracks[0].postGain==1&&e.Snapshot.transportOrigin==count,"Fresh Play did not reset");need(Events(e).Any(x=>x.kind==TrackerEventKind.Row&&x.row==0&&x.samplePosition==count),"Restart event counter reset");}
            });
            check("seek reconstructs clock and column memory; unreachable flow stops",()=>{
                var song=FixtureSong(instrument);Line(song,0,Note());Command(song,0,"ZT",240);Line(song,2,new NoteCell{note=NoteKind.Note,pitch=62});using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,20);e.SendCommand(new TrackerCommand{kind=TrackerCommandKind.Seek,a=0,b=2});e.Render(l,r,20);need(e.Snapshot.bpm==240&&e.Snapshot.voices[0].note==62,"Seek lost inherited scalar/instrument state");need(e.Snapshot.samplePosition==40,"Seek reset absolute counter");}
                Command(song,0,"ZB",0,1);using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play());e.SendCommand(new TrackerCommand{kind=TrackerCommandKind.Seek,a=0,b=2});e.Render(l,r,20);need(!e.Snapshot.playing&&Events(e).Any(x=>x.kind==TrackerEventKind.Diagnostic&&x.payload==(int)TrackerRuntimeDiagnostic.SeekUnreachable),"Unreachable seek guessed state");}
            });
            check("delayed instrument-only writes stay column-local; no-note volume ignores delay",()=>{
                var song=FixtureSong(instrument,2);song.instruments.Add(instrument);Line(song,0,Note(column:0),Note(column:1));Line(song,1,new NoteCell{column=0,instrumentPresent=true,instrument=1,delayPresent=true,delay=128},new NoteCell{column=1,volume=new ColumnValue{kind=ValueKind.Value,value=32},delayPresent=true,delay=128});
                using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,7000);need(e.Snapshot.columns[0].instrument==0&&e.Snapshot.columns[1].instrument==0,"Delayed instrument applied early or crossed column");need(Math.Abs(e.Snapshot.voices[1].volume-.25)<1e-6,"No-note volume was delayed");e.Render(l,r,2100);need(e.Snapshot.columns[0].instrument==1&&e.Snapshot.columns[1].instrument==0,"Instrument-only changed other column");}
            });
            check("NNA per sample, Continue tail isolation and unmapped note preserves foreground",()=>{
                var sample=instrument.model.sampler.samples[0];var zone=instrument.model.sampler.zones[0];var nna=sample.nna;var global=instrument.model.sampler.nna;int max=zone.noteMax;
                try{sample.nna=NewNoteAction.Continue;instrument.model.sampler.nna=NewNoteAction.Cut;zone.noteMax=70;var song=FixtureSong(instrument);Line(song,0,Note());Line(song,1,Note(62));Line(song,2,new NoteCell{volume=new ColumnValue{kind=ValueKind.Value,value=32}});using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,12100);var voices=e.Snapshot.voices.ToArray().Where(x=>x.active).ToArray();need(voices.Length==2&&voices.Single(x=>x.note==60).volume==1&&voices.Single(x=>x.note==62).volume==.25f,"Tail chased foreground setter or global NNA won");e.SendCommand(TrackerCommand.Audition(0,90));e.Render(l,r,20);need(e.Snapshot.voices.ToArray().Count(x=>x.active)==2&&!e.Snapshot.voices[1].released,"Unmapped note detached predecessor");}
                    foreach(var action in new[]{NewNoteAction.Cut,NewNoteAction.NoteOff}){sample.nna=action;using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,6100);need(e.Snapshot.voices.ToArray().Count(x=>x.active)==(action==NewNoteAction.Cut?1:2),"NNA action "+action);}}
                }finally{sample.nna=nna;instrument.model.sampler.nna=global;zone.noteMax=max;}
            });
            check("mute groups cut tails on same track, preserve other tracks and group zero",()=>{
                var sample=instrument.model.sampler.samples[0];var old=sample.nna;int group=sample.muteGroup;sample.nna=NewNoteAction.Continue;sample.muteGroup=1;
                try{var song=FixtureSong(instrument,2);song.tracks.Insert(1,new TrackData{id="second"});song.patterns[0].tracks.Add(new PatternTrack{trackId="second"});Line(song,0,Note());song.patterns[0].tracks.Last().WriteLine(new PatternLine{line=0,notes=new List<NoteCell>{Note()}});Line(song,1,Note(62,column:1));using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,6100);var active=e.Snapshot.voices.ToArray().Where(x=>x.active).ToArray();need(active.Length==2&&active.Any(x=>x.track==1&&x.note==60),"Choke crossed track");}sample.muteGroup=0;using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,6100);need(e.Snapshot.voices.ToArray().Count(x=>x.active)==3,"Zero group choked");}}
                finally{sample.nna=old;sample.muteGroup=group;}
            });
            check("large loop steps fold in bounded time; cubic interpolation differs correctly",()=>{
                var sample=instrument.model.sampler.samples[0];var old=ZTrackerMigration.Copy(sample);try{sample.transpose=120;sample.loopStartFrame=2;sample.loopEndFrame=8;foreach(var loop in new[]{SampleLoop.Forward,SampleLoop.Backward,SampleLoop.PingPong}){sample.loop=loop;using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(FixtureSong(instrument)))){e.SendCommand(TrackerCommand.Audition(0,60));e.Render(l,r,200);need(e.Snapshot.voices[0].position>=2&&e.Snapshot.voices[0].position<8,"Large step loop escape "+loop);}}}
                finally{instrument.model.sampler.samples[0]=old;}
                var clip=AudioClip.Create("cubic-check",32,1,48000,false);var pcm=new float[32];pcm[1]=.2f;pcm[2]=.1f;pcm[3]=.4f;clip.SetData(pcm,0);var a=FixtureInstrument(clip);try{a.model.sampler.samples[0].fineTuneCents=(float)(1200*Math.Log(1.5,2));a.model.sampler.samples[0].interpolation=SampleInterpolation.Cubic;using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(FixtureSong(a)))){e.SendCommand(TrackerCommand.Audition(0,60));e.Render(l,r,2);need(Math.Abs(l[1]-.14375*Math.Sqrt(.5))<1e-6,"Catmull-Rom cubic incorrect "+l[1]);}}finally{UnityEngine.Object.DestroyImmediate(a);UnityEngine.Object.DestroyImmediate(clip);}
            });
            check("all modulation kinds, operations and targets have independent native state",()=>{
                var set=instrument.model.modulation[0];int count=set.devices.Count;try{
                    foreach(var kind in new[]{ModulationDeviceKind.Velocity,ModulationDeviceKind.KeyTracking,ModulationDeviceKind.Fader,ModulationDeviceKind.LFO,ModulationDeviceKind.Multipoint,ModulationDeviceKind.AHDSR}){
                        var mod=new ModulationDevice{kind=kind,target=ModulationTarget.Volume,operation=ModulationOperation.Replace,min=.2f,max=.8f,depth=.5f,rate=2,phase=.25f,attack=0,decay=0,sustain=.5f};mod.points.Add(new ModulationPoint{time=0,value=.5f});mod.points.Add(new ModulationPoint{time=1,value=.5f});set.devices.Add(mod);
                        using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(FixtureSong(instrument)))){e.SendCommand(TrackerCommand.Audition(0,60,64));e.Render(l,r,100);float actual=e.Snapshot.modulationState[0].output;float expected=kind==ModulationDeviceKind.Velocity?.2f+.6f*64/127:kind==ModulationDeviceKind.KeyTracking?.2f+.6f*60/119:kind==ModulationDeviceKind.LFO?.5f*(float)Math.Sin((.25+99d/48000*2)*2*Math.PI):.5f;need(Math.Abs(actual-expected)<1e-5,"Mod kind "+kind+" value "+actual);}
                        set.devices.RemoveAt(count);
                    }
                    foreach(var op in new[]{ModulationOperation.Add,ModulationOperation.Multiply,ModulationOperation.Replace}){set.devices.Add(new ModulationDevice{kind=ModulationDeviceKind.Fader,target=ModulationTarget.Volume,operation=op,depth=.5f});using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(FixtureSong(instrument)))){e.SendCommand(TrackerCommand.Audition(0,60));e.Render(l,r,20);need(Math.Abs(e.Snapshot.voices[0].amplitude-(op==ModulationOperation.Add?1.5:.5))<1e-6,"Mod operation "+op);}set.devices.RemoveAt(count);}
                    foreach(var target in new[]{ModulationTarget.Pan,ModulationTarget.Pitch,ModulationTarget.Cutoff,ModulationTarget.Resonance,ModulationTarget.Drive}){set.devices.Add(new ModulationDevice{kind=ModulationDeviceKind.Fader,target=target,operation=ModulationOperation.Replace,depth=target==ModulationTarget.Cutoff?500:target==ModulationTarget.Pitch?12:.5f});set.filterType=1;using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(FixtureSong(instrument)))){e.SendCommand(TrackerCommand.Audition(0,60));e.Render(l,r,100);need(!float.IsNaN(l[99]),"Nonfinite target "+target);if(target==ModulationTarget.Pitch)need(Math.Abs(e.Snapshot.voices[0].position-200)<1e-6,"Pitch not applied");if(target==ModulationTarget.Cutoff)need(e.Snapshot.voices[0].filterCutoff==500,"Cutoff not applied");if(target==ModulationTarget.Resonance)need(e.Snapshot.voices[0].filterQ==.5f,"Resonance not applied");}set.devices.RemoveAt(count);}
                }finally{while(set.devices.Count>count)set.devices.RemoveAt(count);set.filterType=0;}
            });
            check("multipoint sustain freezes and resumes; loop modes stay within authored bounds",()=>{
                var set=instrument.model.modulation[0];int count=set.devices.Count;var m=new ModulationDevice{kind=ModulationDeviceKind.Multipoint,target=ModulationTarget.Pan,operation=ModulationOperation.Replace,sustainEnabled=true,sustainPosition=.001};m.points.Add(new ModulationPoint{time=0,value=0});m.points.Add(new ModulationPoint{time=.004,value=1});set.devices.Add(m);
                try{using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(FixtureSong(instrument)))){e.SendCommand(TrackerCommand.Audition(0,60));e.Render(l,r,200);need(Math.Abs(e.Snapshot.modulationState[0].output-.25)<1e-6,"Sustain did not freeze");e.SendCommand(new TrackerCommand{kind=TrackerCommandKind.AuditionOff});e.Render(l,r,48);need(e.Snapshot.modulationState[0].output>.48,"Release did not resume from held cursor");}m.sustainEnabled=false;m.loopEnabled=true;m.loopStart=.001;m.loopEnd=.003;foreach(var loop in new[]{SampleLoop.Forward,SampleLoop.Backward,SampleLoop.PingPong}){m.loop=loop;using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(FixtureSong(instrument)))){e.SendCommand(TrackerCommand.Audition(0,60));e.Render(l,r,1000);var pos=e.Snapshot.modulationState[0].position;need(pos>=.001-1d/48000&&pos<=.003+1d/48000,"Mod loop escaped "+loop+" "+pos);}}}
                finally{set.devices.RemoveAt(count);}
            });
            check("trigger mute preserves old voices; output mute processes tails and all taps",()=>{
                var song=FixtureSong(instrument);Line(song,0,Note());song.tracks[0].devices.nodes.Add(new AudioEffectNodeData{type=ZoundEffectType.Delay,p=new[]{1f,.5f,1f,10f,0f}});using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,100);long age=e.Snapshot.voices[0].age;e.SendCommand(new TrackerCommand{kind=TrackerCommandKind.TrackMute,a=0,b=0,c=1});e.SendCommand(TrackerCommand.Audition(0,62));e.Render(l,r,64);need(e.Snapshot.voices.ToArray().Count(x=>x.active)==1&&e.Snapshot.voices[0].age==age+64&&l[63]!=0,"Trigger mute stopped existing voice");e.SendCommand(new TrackerCommand{kind=TrackerCommandKind.TrackMute,a=0,b=1});e.Render(l,r,64);need(l[63]==0&&e.Snapshot.voices[0].age==age+128&&e.Snapshot.chains[0].processor.elapsedSamples==228,"Output mute froze voices/effect history");}
            });
            check("sequence mutes are sample-accurate inside a caller block",()=>{
                var song=FixtureSong(instrument,lines:1);Line(song,0,Note());song.sequence.Add(new SequenceSlot{id="muted",patternId="pattern",mutedTrackIds=new List<string>{"notes"}});using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,6500,6500);need(l[5999]!=0&&l[6000]==0&&l[6499]==0,"Final sequence mute smeared whole block");need(e.Snapshot.voices[0].age==6500,"Sequence mute froze old voice");}
            });
            check("prefader and postfader insertion taps share smooth live faders",()=>{
                foreach(bool post in new[]{false,true}){var song=FixtureSong(instrument);song.tracks.Insert(1,new TrackData{id="send",kind=TrackKind.Send,visibleNoteColumns=0});song.patterns[0].tracks.Add(new PatternTrack{trackId="send"});song.tracks[0].sends.Add(new SendDestination{trackId="send",devicePosition=0,gain=.5f,postfader=post});Line(song,0,Note());using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,64);e.SendCommand(new TrackerCommand{kind=TrackerCommandKind.TrackGain,a=0,value=0});e.Render(l,r,64,17);need(l[0]>l[31]&&Math.Abs(l[63]-(post?0:.05*Math.Sqrt(.5)))<1e-6,"Fader/send ramp "+post);need(e.Snapshot.tracks[0].livePostGain==0,"Ramp did not finish");}}
            });
            check("modern stereo center unity, additive layers, no hidden normalization",()=>{
                var clip=AudioClip.Create("modern-stereo",1024,2,48000,false);var values=Enumerable.Repeat(.1f,2048).ToArray();clip.SetData(values,0);var a=FixtureInstrument(clip);a.model.provenance="";a.model.sampler.zones.Add(ZTrackerMigration.Copy(a.model.sampler.zones[0]));
                try{using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(FixtureSong(a)))){e.SendCommand(TrackerCommand.Audition(0,60));e.Render(l,r,64);need(Math.Abs(l[63]-.2)<1e-6&&Math.Abs(r[63]-.2)<1e-6&&!e.Snapshot.legacyMix,"Modern mix inherited legacy automatic gain/pan");}}finally{UnityEngine.Object.DestroyImmediate(a);UnityEngine.Object.DestroyImmediate(clip);}
            });
            check("all sixteen AudioCore effects and five bound modifiers compile and run finite",()=>{
                for(int type=0;type<16;type++){var song=FixtureSong(instrument);Line(song,0,Note());song.tracks[0].devices.nodes.Add(new AudioEffectNodeData{type=(ZoundEffectType)type});using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,1024);need(e.Compiled&&l.ToArray().Take(1024).All(x=>!float.IsNaN(x)&&!float.IsInfinity(x)),"Effect "+type);}}
                for(int type=0;type<5;type++){var song=FixtureSong(instrument);Line(song,0,Note());song.tracks[0].devices.nodes.Add(new AudioEffectNodeData{type=ZoundEffectType.Gain});song.tracks[0].devices.modifiers.Add(new AudioModifierData{type=(ZoundModifierType)type});song.tracks[0].devices.bindings.Add(new AudioModifierBindingData{nodeIndex=0,modifierIndex=0,paramIndex=0,schema=2,combine=ModulationCombine.Set,depth=1});using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,1024);need(!float.IsNaN(l[63])&&e.Snapshot.chains[0].processor.elapsedSamples==1024,"Modifier "+type);}}
            });
            check("FX cadence independent from tracker tick cuts; caller partition sensitivity measured",()=>{
                Func<int,float[]> render=tpl=>{var song=FixtureSong(instrument);song.ticksPerLine=tpl;Line(song,0,Note());song.tracks[0].devices.nodes.Add(new AudioEffectNodeData{type=ZoundEffectType.Phaser});using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,20000,1024);return l.ToArray().Take(20000).ToArray();}};
                var a=render(1);var b=render(6);need(a.Zip(b,(x,y)=>Math.Abs(x-y)).Max()<1e-7,"Tick slices changed FX cadence");
                var song=FixtureSong(instrument);Line(song,0,Note());song.tracks[0].devices.nodes.Add(new AudioEffectNodeData{type=ZoundEffectType.Phaser});using(var e=new TrackerOffline(TrackerPreparedSong.Prepare(song))){e.SendCommand(TrackerCommand.Play());e.Render(l,r,20000,333);var different=l.ToArray().Take(20000).Zip(a,(x,y)=>Math.Abs(x-y)).Max();report.AppendLine("MEASURE phaserCaller333vs1024MaxError="+different.ToString("R",System.Globalization.CultureInfo.InvariantCulture));}
            });
            check("quiet ticket movement/odd rejects, timeout retains owner, quit needs real frames and time",()=>{
                using(var p=TrackerPreparedSong.Prepare(FixtureSong(instrument))){p.Published=true;bool refused=false;try{p.Dispose();}catch(InvalidOperationException){refused=true;}need(refused&&!p.Disposed,"Published disposal freed owner");SapRenderTicket.Enter(p.state.ticket);need(!p.WaitUntilQuiet(.01,.02)&&!p.Disposed,"Odd ticket timeout freed memory");SapRenderTicket.Exit(p.state.ticket,0,false);p.Published=false;}
                var quiet=new SapQuietWindow();need(!quiet.Observe(2,0,.06)&&!quiet.Observe(4,.05,.06)&&!quiet.Observe(4,.10,.06)&&quiet.Observe(4,.12,.06),"Quiet did not restart on movement");var drain=new SapQuitDrain();drain.Begin(10);need(!drain.Tick(10.4)&&drain.Tick(10.41)&&drain.RefuseNewRendering,"Quit skipped actual two frame ticks");
            });
            check("malformed visible columns, bank indices, chain curves and capacities reject",()=>{
                Action<SongData> rejected=s=>{bool bad=false;try{using(var p=TrackerPreparedSong.Prepare(s)){} }catch(ArgumentException){bad=true;}need(bad,"Malformed layout was published");};var song=FixtureSong(instrument);Line(song,0,Note(column:1));rejected(song);song=FixtureSong(instrument);var note=Note();note.instrument=1;Line(song,0,note);rejected(song);song=FixtureSong(instrument);song.voiceCapacity=4097;rejected(song);song=FixtureSong(instrument);song.tracks[0].devices.nodes.Add(new AudioEffectNodeData{type=ZoundEffectType.Gain});var mod=new AudioModifierData{type=ZoundModifierType.Envelope};mod.curve.m_points.Add(new AudioEnvelopePointData{time=0,value=1,exponent=1});mod.curve.m_points.Add(new AudioEnvelopePointData{time=0,value=0,exponent=1});song.tracks[0].devices.modifiers.Add(mod);rejected(song);
            });
        }
    }
}
