// <auto-generated> Laubrary Zoetrope state names - do not edit. </auto-generated>
// Source: Assets/Demos/PreviewDemo/PreviewTargetZoe.asset  (GUID b4b8c5e9aa5985942ac604330e395f6e)
// Rewritten every time that asset is saved. Rename a state in the Zoe window and this file
// follows it; the same name re-typed as a string literal in game code would not, and would
// fail silently at runtime instead of loudly at compile time.

namespace ZoeStates
{
    /// The states <c>PreviewTargetZoe</c> declares, for asking it to show one by name.
    /// Hit and death are deliberately absent: they are fixed slots on the character, not names,
    /// so asking for them by name resolves to nothing.
    public static class PreviewTargetZoeStates
    {
        // This character declares no custom event states yet. Add one under Custom events
        // in the Zoe window and it appears here on the next save.

        /// Every state name above, in the order the character declares them.
        public static readonly string[] All = { };
    }
}
