// <auto-generated>
// This code was generated by SimpleUI Property Generator
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

namespace Laubrary.SimpleUI.Demo
{
    public partial class PocoGenerationDemo
    {
        public int health
        {
            get => _health;
            set => SetField(ref _health, value);
        }

        public float stamina
        {
            get => _stamina;
            set => SetField(ref _stamina, value);
        }

        public bool isAlive
        {
            get => _isAlive;
            set => SetField(ref _isAlive, value);
        }

        public CharacterClass characterClass
        {
            get => _characterClass;
            set => SetField(ref _characterClass, value);
        }

        [SimpleUIFormat("Level {0}")]
        public int level
        {
            get => _level;
            set => SetField(ref _level, value);
        }

        [SimpleUIFormat("Gold: {0:N0}")]
        public int gold
        {
            get => _gold;
            set => SetField(ref _gold, value);
        }

        [SimpleUIPath("Stats/Details/ExperienceBar")]
        [SimpleUIFormat("XP: {0}/1000")]
        public int experience
        {
            get => _experience;
            set => SetField(ref _experience, value);
        }

        [SimpleUIPath("CharacterNameLabel")]
        [SimpleUIPath("CharacterNameInput")]
        public string characterName
        {
            get => _characterName;
            set => SetField(ref _characterName, value);
        }

    }
}
