// <auto-generated> Laubrary Zoetrope state names - do not edit. </auto-generated>
// Source: Assets/Demos/ProtoGuyDemo/ProtoGuy.asset  (GUID 29e5104593a1376479445b0902ba1078)
// Rewritten every time that asset is saved. Rename a state in the Zoe window and this file
// follows it; the same name re-typed as a string literal in game code would not, and would
// fail silently at runtime instead of loudly at compile time.

namespace ZoeStates
{
    /// The states <c>ProtoGuy</c> declares, for asking it to show one by name.
    /// Hit and death are deliberately absent: they are fixed slots on the character, not names,
    /// so asking for them by name resolves to nothing.
    public static class ProtoGuyStates
    {
        /// Raised as <c>Fire</c>.
        public const string Fire = "Fire";

        /// Every state name above, in the order the character declares them.
        public static readonly string[] All = { "Fire" };
    }
}
