using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Laubrary.Zoetrope.Editor
{
    /// Writes a `.states.cs` file next to every Zoe asset - `ProtoGuy.asset` gets `ProtoGuy.states.cs` - listing
    /// that character's declared state names as constants, and rewrites it whenever the asset is saved.
    ///
    /// The bug it exists to stop: a state name is typed ONCE, on the character, under Custom events - and then
    /// re-typed as a bare string in game code (`Raise("Shooting Lazer")`). Rename the state in the Zoe window
    /// and the character is correct while the code still asks for a name nobody declares any more. Nothing
    /// fails to compile; it just quietly stops playing. `ZoeStates.ProtoGuyStates.ShootingLazer` fails at
    /// COMPILE time instead, which is the whole point: the rename cannot outrun the reference.
    ///
    /// Why a sibling file rather than one central list: a file dropped beside the asset joins whatever asmdef
    /// that folder already belongs to (a Zoe in `Assets/Demos/` joins `Laubrary.Demos`), which is the same
    /// assembly the code using that character lives in. A single central file would land in Assembly-CSharp
    /// and be invisible to every game asmdef - the constants would exist and nobody could reference them.
    ///
    /// Nothing here has a menu item: a list you have to remember to regenerate is a list that goes stale, which
    /// is the failure this whole file is about.
    class ZoeStateNamesGenerator : AssetPostprocessor
    {
        const string GeneratedSuffix = ".states.cs";
        const string Namespace = "ZoeStates";

        /// First line of every file we write. Orphan cleanup deletes ONLY files carrying it, so a hand-written
        /// file that happens to end in `.states.cs` is never destroyed by this tool. Kept pure ASCII: this one
        /// string gates a delete, and it has to survive any encoding round-trip a checkout puts it through.
        const string Marker = "// <auto-generated> Laubrary Zoetrope state names - do not edit. </auto-generated>";

        // ---------------------------------------------------------------------------------------------
        // Triggers
        // ---------------------------------------------------------------------------------------------

        static void OnPostprocessAllAssets(string[] imported, string[] deleted, string[] moved, string[] movedFrom)
        {
            // Writing a .cs during Play kills the session (it forces a domain reload mid-play). The exit-play
            // hook below catches up whatever was missed.
            if (EditorApplication.isPlayingOrWillChangePlaymode) return;

            if (!AnyZoe(imported) && !AnyZoe(moved) && !AnyGoneAsset(deleted) && !AnyGoneAsset(movedFrom)) return;
            Schedule(reportStale: false);
        }

        [InitializeOnLoadMethod]
        static void Hook()
        {
            // After every assembly reload, confirm on disk what the code now claims. This is what catches a
            // generated file someone hand-edited, or one a merge mangled - cases the postprocessor never sees,
            // because it deliberately ignores .cs imports (reacting to them would mean rewriting the file we
            // just wrote, forever).
            Schedule(reportStale: true);

            EditorApplication.playModeStateChanged += s =>
            {
                if (s == PlayModeStateChange.EnteredEditMode) Schedule(reportStale: false);
            };
        }

        static bool _pending, _reportStale;

        /// Defer to the next editor tick. Writing and deleting assets from inside `OnPostprocessAllAssets` is
        /// re-entrant into the importer that is currently running; off the callback it is ordinary editor work.
        ///
        /// Deliberately a one-shot `EditorApplication.update` subscription and NOT `delayCall`. A `delayCall`
        /// registered from `[InitializeOnLoadMethod]` is discarded by Unity when initialization finishes, so
        /// the post-reload verify pass never ran at all — and because `_pending` had already latched to true,
        /// every later postprocessor callback took the early return, so NOTHING was ever generated
        /// automatically. Measured, not theorised: with `delayCall`, saving a Zoe produced no file and a domain
        /// reload produced none either, while invoking `Sync` by hand produced all six correctly. `update`
        /// unsubscribes itself in `Tick`, so the latch can never outlive the work it was guarding.
        static void Schedule(bool reportStale)
        {
            _reportStale |= reportStale;
            if (_pending) return;
            _pending = true;
            EditorApplication.update += Tick;
        }

        static void Tick()
        {
            // Unsubscribed FIRST, so a Sync that throws cannot leave this running every frame forever.
            EditorApplication.update -= Tick;
            _pending = false;
            bool stale = _reportStale;
            _reportStale = false;
            Sync(stale);
        }

        static bool AnyZoe(string[] paths)
        {
            if (paths == null) return false;
            foreach (var p in paths)
            {
                var t = AssetDatabase.GetMainAssetTypeAtPath(p);
                if (t != null && typeof(Zoe).IsAssignableFrom(t)) return true;
            }
            return false;
        }

        /// A deleted or moved-from path can no longer be type-tested - the asset is gone. Any vanished `.asset`
        /// is treated as possibly-a-Zoe; the sync that follows is cheap and is what removes the orphan.
        static bool AnyGoneAsset(string[] paths)
        {
            if (paths == null) return false;
            foreach (var p in paths)
                if (p.EndsWith(".asset", System.StringComparison.OrdinalIgnoreCase)) return true;
            return false;
        }

        // ---------------------------------------------------------------------------------------------
        // The one pass that does everything
        // ---------------------------------------------------------------------------------------------

        struct Wanted
        {
            public string Path;        // project-relative path of the generated file
            public string Text;
            public Object Owner;       // log context: clicking the message selects the character
            public string OwnerPath;
        }

        /// One whole-project pass handles write, rewrite, rename, move, delete and name collision alike.
        /// Splitting it into per-event handlers is exactly what lets a move leave an orphan behind: the
        /// "deleted" half and the "created" half each look correct on their own.
        static void Sync(bool reportStale)
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode) return;

            var wanted = new List<Wanted>();
            var wantedPaths = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);

            // Class name -> the asset that got there first. Two Zoe assets with the same file name would emit
            // two `ZoeStates.FooStates` classes; emitting both stops the whole project compiling, so the second
            // is reported and skipped instead.
            var claimed = new Dictionary<string, string>(System.StringComparer.OrdinalIgnoreCase);

            var paths = new List<string>();
            foreach (var guid in AssetDatabase.FindAssets("t:Zoe"))
            {
                var p = AssetDatabase.GUIDToAssetPath(guid);
                if (IsGeneratableLocation(p)) paths.Add(p);
            }
            paths.Sort(System.StringComparer.Ordinal);   // stable: same project, same winner of a name clash

            foreach (var p in paths)
            {
                var zoe = AssetDatabase.LoadAssetAtPath<Zoe>(p);
                if (zoe == null) continue;

                string className = Identifier(Path.GetFileNameWithoutExtension(p), "Zoe") + "States";
                if (claimed.TryGetValue(className, out var firstOwner))
                {
                    Debug.LogError(
                        $"[Zoe] '{p}' and '{firstOwner}' both generate the state-name class {Namespace}.{className}, " +
                        "so only the first one got a list. Rename one of the assets: two classes with the same " +
                        "name would stop the project compiling.", zoe);
                    continue;                            // its stale file, if any, is collected as an orphan below
                }
                claimed[className] = p;

                var w = new Wanted
                {
                    Path = GeneratedPathFor(p),
                    Text = BuildSource(zoe, p, className),
                    Owner = zoe,
                    OwnerPath = p,
                };
                wanted.Add(w);
                wantedPaths.Add(w.Path);
            }

            foreach (var w in wanted) WriteIfNeeded(w, reportStale);
            RemoveOrphans(wantedPaths);
        }

        /// Generated output belongs beside the character it describes, in the host project. A Zoe living inside
        /// the package is library content: writing next to it would drop a host-project artefact into the folder
        /// that gets copied wholesale into consumer projects.
        static bool IsGeneratableLocation(string assetPath)
        {
            if (string.IsNullOrEmpty(assetPath)) return false;
            if (!assetPath.StartsWith("Assets/", System.StringComparison.OrdinalIgnoreCase)) return false;   // a UPM package folder is read-only
            if (assetPath.StartsWith("Assets/Packages/", System.StringComparison.OrdinalIgnoreCase)) return false;
            return true;
        }

        static string GeneratedPathFor(string assetPath)
        {
            int dot = assetPath.LastIndexOf('.');
            return (dot < 0 ? assetPath : assetPath.Substring(0, dot)) + GeneratedSuffix;
        }

        static void WriteIfNeeded(Wanted w, bool reportStale)
        {
            string abs = ToAbsolute(w.Path);
            string existing = File.Exists(abs) ? File.ReadAllText(abs) : null;

            if (existing != null && Normalize(existing) == Normalize(w.Text)) return;

            // A file that is merely BEHIND its asset is normal - you just renamed a state and this is the
            // rewrite. A file NEWER than its asset that still disagrees with it was changed by something other
            // than this generator: a hand-edit, or a merge taking the wrong side. That one is an error, because
            // until it is rewritten the constants inside it are a lie the compiler will happily accept.
            if (existing != null && reportStale && IsNewerThanItsAsset(abs, ToAbsolute(w.OwnerPath)))
            {
                Debug.LogError(
                    $"[Zoe] '{w.Owner.name}': the generated state-name list '{w.Path}' no longer matches the " +
                    "character and was changed outside this generator (a hand-edit, or a merge). It has been " +
                    "rewritten from the asset. Edit the states under Custom events in the Zoe window, never this file.",
                    w.Owner);
            }

            Directory.CreateDirectory(Path.GetDirectoryName(abs));
            File.WriteAllText(abs, w.Text);
            AssetDatabase.ImportAsset(w.Path, ImportAssetOptions.ForceUpdate);
        }

        static bool IsNewerThanItsAsset(string generatedAbs, string assetAbs)
        {
            if (!File.Exists(assetAbs)) return true;
            return File.GetLastWriteTimeUtc(generatedAbs) > File.GetLastWriteTimeUtc(assetAbs);
        }

        /// Delete a Zoe and its generated list must go too, or code still compiles against a character that no
        /// longer exists - the same stale reference this generator exists to prevent, just from the other end.
        static void RemoveOrphans(HashSet<string> wantedPaths)
        {
            string root = Application.dataPath.Replace('\\', '/').TrimEnd('/');
            string[] found;
            try { found = Directory.GetFiles(root, "*" + GeneratedSuffix, SearchOption.AllDirectories); }
            catch (System.Exception e) { Debug.LogWarning($"[Zoe] Could not scan for orphaned state-name lists: {e.Message}"); return; }

            foreach (var abs in found)
            {
                // Windows wildcard matching can over-match via 8.3 short names, so the suffix is re-checked here
                // rather than trusted from the search pattern. Separators are normalised because GetFiles returns
                // whatever mixture of '/' and '\' the root and the walk happen to produce.
                string norm = abs.Replace('\\', '/');
                if (!norm.EndsWith(GeneratedSuffix, System.StringComparison.OrdinalIgnoreCase)) continue;
                if (!norm.StartsWith(root, System.StringComparison.OrdinalIgnoreCase)) continue;

                string rel = "Assets" + norm.Substring(root.Length);
                if (wantedPaths.Contains(rel)) continue;
                if (!CarriesMarker(abs)) continue;       // somebody else's file that merely shares the suffix

                if (AssetDatabase.DeleteAsset(rel))
                    Debug.Log($"[Zoe] Removed '{rel}': the character it listed states for is gone.");
            }
        }

        static bool CarriesMarker(string abs)
        {
            try
            {
                using (var r = new StreamReader(abs))
                {
                    var first = r.ReadLine();
                    return first != null && first.Trim('\uFEFF', ' ').StartsWith(Marker);
                }
            }
            catch { return false; }
        }

        static string ToAbsolute(string projectRelative) =>
            Path.Combine(Path.GetDirectoryName(Application.dataPath) ?? string.Empty, projectRelative);

        /// Line endings and a byte-order mark are not content. Without this, a checkout that rewrote LF to CRLF
        /// would make every generated file look hand-edited and log an error per character on every reload.
        static string Normalize(string s) =>
            s == null ? null : s.Replace("\r", string.Empty).Trim('\uFEFF');

        // ---------------------------------------------------------------------------------------------
        // The generated text
        // ---------------------------------------------------------------------------------------------

        static string BuildSource(Zoe zoe, string assetPath, string className)
        {
            // Member name -> the id that claimed it. OrdinalIgnoreCase because Zoe name matching is
            // case-insensitive: "Fire" and "fiRE" are ONE state, so a constant for each would promise two
            // states that resolve to the same reaction.
            var members = new Dictionary<string, string>(System.StringComparer.OrdinalIgnoreCase);
            var body = new StringBuilder();
            var all = new List<string>();

            var events = zoe.events;
            for (int i = 0; events != null && i < events.Count; i++)
            {
                var e = events[i];
                // An empty id can never be raised (Zoe.EventNamed rejects it) and the Zoe window already badges
                // it where it can be fixed; a constant for it would just be a second complaint.
                if (e == null || string.IsNullOrEmpty(e.id)) continue;

                string member = Identifier(e.id, "State");
                if (members.TryGetValue(member, out var firstId))
                {
                    Debug.LogError(
                        $"[Zoe] '{zoe.name}' declares two states this character cannot tell apart: \"{firstId}\" " +
                        $"and \"{e.id}\". Only the first can ever play. Rename one under Custom events.", zoe);
                    all.Add(e.id);                       // still listed in All, so the list stays honest about what is authored
                    continue;
                }
                members[member] = e.id;

                if (body.Length > 0) body.Append('\n');
                body.Append("        /// Raised as <c>").Append(XmlEscape(e.id)).Append("</c>.\n");
                body.Append("        public const string ").Append(member)
                    .Append(" = \"").Append(Escape(e.id)).Append("\";\n");
                all.Add(e.id);
            }

            var sb = new StringBuilder();
            sb.Append(Marker).Append('\n');
            sb.Append("// Source: ").Append(assetPath).Append("  (GUID ").Append(AssetDatabase.AssetPathToGUID(assetPath)).Append(")\n");
            sb.Append("// Rewritten every time that asset is saved. Rename a state in the Zoe window and this file\n");
            sb.Append("// follows it; the same name re-typed as a string literal in game code would not, and would\n");
            sb.Append("// fail silently at runtime instead of loudly at compile time.\n");
            sb.Append('\n');
            sb.Append("namespace ").Append(Namespace).Append('\n');
            sb.Append("{\n");
            sb.Append("    /// The states <c>").Append(XmlEscape(zoe.name)).Append("</c> declares, for asking it to show one by name.\n");
            sb.Append("    /// Hit and death are deliberately absent: they are fixed slots on the character, not names,\n");
            sb.Append("    /// so asking for them by name resolves to nothing.\n");
            sb.Append("    public static class ").Append(className).Append('\n');
            sb.Append("    {\n");

            if (body.Length == 0)
                sb.Append("        // This character declares no custom event states yet. Add one under Custom events\n")
                  .Append("        // in the Zoe window and it appears here on the next save.\n");
            else
                sb.Append(body.ToString());   // not Append(StringBuilder): that overload is not on every API level Unity ships

            sb.Append('\n');
            sb.Append("        /// Every state name above, in the order the character declares them.\n");
            sb.Append("        public static readonly string[] All = {");
            for (int i = 0; i < all.Count; i++)
                sb.Append(i == 0 ? " " : ", ").Append('"').Append(Escape(all[i])).Append('"');
            sb.Append(" };\n");

            sb.Append("    }\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// An authored name may hold anything a text field accepts; a C# member name may not. ASCII-only,
        /// deliberately: an illegal identifier here does not produce an ugly name, it stops the entire project
        /// compiling, so anything not provably legal is dropped rather than passed through and hoped for.
        /// Word breaks capitalise, so "Shooting Lazer" becomes ShootingLazer. That also means the result always
        /// starts upper-case or with '_', and every C# keyword is lower-case, so a generated name can never
        /// collide with a keyword.
        static string Identifier(string raw, string fallbackPrefix)
        {
            var sb = new StringBuilder(raw != null ? raw.Length : 0);
            bool wordStart = true;

            for (int i = 0; raw != null && i < raw.Length; i++)
            {
                char c = raw[i];
                bool ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_';
                if (!ok) { wordStart = true; continue; }
                sb.Append(wordStart ? char.ToUpperInvariant(c) : c);
                wordStart = false;
            }

            // Nothing usable survived (a name written entirely in punctuation, or in a non-Latin script). A
            // stable fingerprint keeps it referenceable and keeps two such names apart, instead of collapsing
            // every one of them onto a single member.
            if (sb.Length == 0) return fallbackPrefix + Fingerprint(raw);
            if (sb[0] >= '0' && sb[0] <= '9') sb.Insert(0, '_');
            return sb.ToString();
        }

        /// FNV-1a, written out rather than using string.GetHashCode, which is not guaranteed stable across
        /// runtimes: an unstable one would rewrite the file, and so recompile the project, at random.
        /// Lower-cased first, so two names differing only in case fingerprint the same and are caught as the
        /// duplicate they are under case-insensitive matching.
        static string Fingerprint(string raw)
        {
            uint h = 2166136261;
            string s = raw == null ? string.Empty : raw.ToLowerInvariant();
            for (int i = 0; i < s.Length; i++) { h ^= s[i]; h *= 16777619; }
            return h.ToString("x8");
        }

        static string Escape(string s) =>
            s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r").Replace("\t", "\\t");

        /// A name holding an angle bracket or an ampersand turns the generated doc comment into malformed XML,
        /// so the doc text gets escaped even though the string literal beside it does not need it.
        static string XmlEscape(string s) =>
            (s ?? string.Empty).Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
    }
}
