import io
p = r'D:\UNITY\Laubrary Dev\.agenthq\workspace\T-0106\FILL-CONTRACT.md'
s = io.open(p, encoding='utf-8').read()

anchor26 = "with `coverageEff` clamped to [0,1] at this point and only at this point (FC-2.4a). An implementation MAY carry the destination premultiplied internally to avoid the divide \u2014 that is a representation choice inside the compositor and it does not change the fill's contract, which hands over non-premultiplied albedo.\n"
assert anchor26 in s, "FC-2.6a anchor"
add26 = anchor26 + """
**FC-2.6a-AMENDED [T-0106 fix pass, 2026-08-31] \u2014 `Over` describes how a FINISHED layer meets what is beneath it, and never how one silhouette's own exclusive owners meet each other.** The formula above is unchanged and remains correct for what it actually governs. What is amended is its SCOPE.

*The superseded reading, recorded so it is not re-derived by accident:* FC-2.6a was read \u2014 by the T-0106 implementation, and defensibly, since nothing here said otherwise \u2014 as the rule for compositing EVERY fill against the accumulated destination, including two fills that own disjoint parts of the same silhouette by FC-3.5. *Why that reading is wrong:* `outA = coverageEff + dstA \u00b7 (1 \u2212 coverageEff)` is the accumulation of two INDEPENDENT coverages. Exclusive owners do not hold independent coverages; by FC-3.5 they hold a PARTITION of one pixel's area, and the accumulation of a partition is the sum. Asking `Over` about a partition under-reports, and the under-report is not a rounding residue: **measured on the FT-21 fixture, 244 of 16384 samples came out below the shape's own published coverage, total alpha deficit 29.288, worst 0.2484** \u2014 a one-pixel ring up to 25% transparent wherever one fill's region met another's inside a single silhouette. The arithmetic is the plainest statement of it: an ancestor at 0.5 and a descendant at 0.5 give `0.5 + 0.5 \u00b7 0.5 = 0.75` where the shape's own coverage is exactly 1.0.

*What now holds:* within one silhouette's paint pass the owners accumulate by claim-weighted sum (FC-3.5a); `Over` then describes the relationship of a finished subtree to what is under it \u2014 to a sibling subtree, and to the destination. Both halves are FC-2.6a's formula applied where it is true. Re-measured after the change, same instrument and same fixture: **0 of 16384 samples, total deficit 0.000, worst 0.0000**, with the sibling half unmoved \u2014 two overlapping siblings at veil 0.5 still read alpha 0.75000, which is `Over` and not a sum.
"""
s = s.replace(anchor26, add26, 1)

anchor35 = "The alternative \u2014 the ancestor painting a backdrop that a translucent descendant shows through \u2014 is superficially attractive and wrong for two reasons. It makes one fill do two jobs (surface *and* backdrop) with no way to author \"descendant over transparent\", which is the double-meaning FC-2.2 refused. And it makes resolution O(depth) per pixel instead of O(1), because every ancestor in the chain must be evaluated at every pixel of the deepest descendant. If layered paint is wanted, that is what a second node is for \u2014 and it is expressible today, by adding a member that duplicates the silhouette and carries the upper fill.\n"
assert anchor35 in s, "FC-3.5 anchor"
add35 = anchor35 + """
**FC-3.5a [T-0106 fix pass, 2026-08-31] \u2014 exclusive owners ACCUMULATE BY CLAIM-WEIGHTED SUM, not by `Over`.** This is the clause FC-3.5 always implied and never said, and its absence is what let the seam through.

> An owner's paint region is `max(0, claim \u2212 descendantClaim)`, which by construction is DISJOINT from every one of its descendants' regions. Disjoint sub-areas of one pixel are parts of one whole, so their alphas ADD and their colours average by claim: `alpha = \u03a3 claim_o` and `rgb = \u03a3 claim_o \u00b7 albedo_o` (premultiplied). SIBLING claims, by contrast, genuinely overlap and are NOT a partition, so siblings still composite `Over` in fold order (FC-3.4), and a finished subtree still meets the destination with `Over` (FC-2.6a as amended).

*The superseded reading:* that "exactly ONE owner per pixel" was fully discharged by making the claims disjoint, and that the compositor could then treat every owner uniformly. It cannot \u2014 making the regions disjoint and then compositing them as if they were independent throws the disjointness away again at the last step. *The measurement that forced the amendment:* 244/16384 samples, deficit 29.288, worst 0.2484, now 0/16384, deficit 0.000, worst 0.0000; the numbers in FC-2.6a-AMENDED, from the same instrument on the same fixture.

*What it costs, stated rather than hidden:* one 4-float-per-sample accumulator per owner (`ShaperFillBuffers.subtree`), because a subtree has to be finished before it can meet a sibling and a single flat destination cannot tell an ancestor from a sibling once both are mixed into it. Host-allocated once, on the same BC-3.7f terms as every other array; nothing is allocated inside a paint call and FT-9's IL scan is unchanged.

*One consequence that is a limitation and not a bug:* `descendantClaim` is a MAX over the descendants rather than a sum, because siblings may overlap and a sum would double-count them. Two SPATIALLY DISJOINT descendants at fractional coverage can therefore leave their ancestor more claim than the pixel has left, and the accumulated alpha is clamped at 1 at use (FC-2.4a's argument \u2014 alpha past total opacity has no meaning). RGB is deliberately not rescaled to match, because an additive result legitimately carries more light than its alpha.

**FC-3.5b [T-0106 fix pass, 2026-08-31] \u2014 the mixed case, defined rather than left to fall out.** Where one owner of a pixel declares `Over` and another declares `Add`, **the pixel's alpha is the sum of the `Over` owners' claims alone, and its RGB is the claim-weighted sum of EVERY owner's albedo.** An `Add` owner contributes light and never opacity \u2014 whether it meets the destination, a sibling, or an ancestor that shares the pixel with it. This is FC-2.6b's "Add does not increase alpha" carried unchanged into the partition, and it is written down because it is the one combination a reader would otherwise have to derive. Consequence worth naming: a silhouette whose only fill is additive stays fully transparent and fully bright, which is exactly what FC-2.6b asks for, and FT-17 still measures `alpha == 0` across all 16384 samples.
"""
s = s.replace(anchor35, add35, 1)

anchor23 = "**The escape hatch, named rather than built.** Both conversions live at exactly two named boundaries, one function each. If the owner would rather have byte-for-byte Pyre parity than correct compositing, making both functions the identity is a two-line change at two sites and no other code moves. **Do not add a dial for this.** A colour-space mode is a document-wide correctness property, not a per-fill preference, and adding a switch would mean every conformance test in \u00a7F7 has to run twice.\n"
assert anchor23 in s, "FC-2.3 anchor"
add23 = anchor23 + """
**FC-2.3a [T-0106 fix pass, 2026-08-31] \u2014 the `Color32` write is STRAIGHT ALPHA, and there is exactly ONE of it.** FC-2.3 says albedo is non-premultiplied and that the encode happens once at the document's `Color32` write; it did not say which alpha convention those bytes carry, and the first implementation shipped two encoders and made the wrong one the default.

*The superseded state:* `EncodePremultiplied` was the default. It premultiplied in LINEAR and then sRGB-encoded the premultiplied value \u2014 `encode(rgb \u00b7 \u03b1)` \u2014 which is neither straight alpha nor the conventional premultiplied-sRGB `encode(rgb) \u00b7 \u03b1`, so neither kind of consumer could read it back. *Measured, linear-white fill, byte per alpha:* \u03b1 = 0.75 gives 225 where straight wants 255 and conventional premultiplied wants 191; \u03b1 = 0.5 gives 188 against 255 and 128; \u03b1 = 0.25 gives 137 against 255 and 64; \u03b1 = 0.1 gives 89 against 255 and 26. At \u03b1 = 0.5 a premultiplied consumer reconstructs 1.47\u00d7 too bright and a straight-alpha consumer 26% too dark; over all 256 codes at \u03b1 = 0.5 the worst straight-alpha misread was **67 codes**, and it is now **0**.

*What now holds:* one function, `ShaperFillResolver.Encode`, un-premultiplying in linear and encoding once, producing straight-alpha bytes. That is what FC-2.3 specifies, what a PNG requires (the format has no premultiplied mode to declare), and what Unity's `SrcAlpha OneMinusSrcAlpha` sprite blend consumes. The premultiplied encoder was **deleted**, not repaired, and the reason is worth keeping: its justification was that only premultiplication can represent an additive glow over nothing (\u03b1 = 0, RGB > 0, FC-2.6b), and that is true of premultiplication and false of any correct 8-bit encoding of it \u2014 the conventional premultiplied byte for that sample is `encode(rgb) \u00b7 0 = 0`, which deletes the glow just as thoroughly. Keeping a second encoder would have traded a documented limitation for an undocumented misencoding, and it had no caller.

*Where the additive case lives instead \u2014 both answers are real and both are in use:* read the float destination directly, which is linear premultiplied and carries the glow exactly, and is what a light stage or a further composite should consume; or composite over an opaque backdrop BEFORE the encode, at which point the glow is ordinary brightness and every byte is meaningful (the contact sheet does exactly this, which is the only reason an additive cell can be shown at all). `Encode`'s own `\u03b1 \u2264 1e-6` branch does not divide, so an additive sample keeps its colour bytes and honestly reports \u03b1 = 0; a straight-alpha blender will discard it, and that is the limitation rather than a third answer.
"""
s = s.replace(anchor23, add23, 1)

io.open(p, 'w', encoding='utf-8', newline='').write(s)
print("contract amended, chars =", len(s))
