using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Laubrary.Zounds.Uitk {

    /// <summary>
    /// Copies the Zounds windows' look into a USS stylesheet and a handful of textures, ONCE, for the UI Toolkit port
    /// (T-0457). The owner's decision (2026-09-28): "use a USS copy the exact visuals from the old imgui but only use
    /// UiTK" — the new windows carry a copy of the look, and never read the Zounds style sheet while running.
    ///
    /// **What it copies.** For each button style the old windows use (RichButton, RichToggle, ...), for each state
    /// (normal, hover, pressed, toggled on): the exact fill texture the old ZUI draws with (so a gradient is the very
    /// same pixels), the resolved text colour, size and weight, the border, the corner radius and which corners are
    /// rounded, and the padding. For each slider style: the track and fill boxes and the label text. Plus the named
    /// palette colours as USS variables. The result is <c>Skin/ZoundsSkin.uss</c> and PNGs beside it.
    ///
    /// **Why a generator and not a hand-written file.** Resolving a style by hand means following palette references,
    /// derived shades, gradient stops and state fall-backs (hover falls back to normal, pressed to hover, on to pressed)
    /// — exactly the kind of thing a person copies wrongly. The generator asks the old ZUI for the answers it draws with.
    /// Run it again only if the old look is deliberately changed; the generated file says so at the top.
    ///
    /// Called from code (no menu item): <c>ZoundsSkinExtractor.Generate()</c>.
    /// </summary>
    public static class ZoundsSkinExtractor {

        public const string SheetPath = "Assets/Packages/Laubrary/Editor/Zounds/ZUI Assets/ZOUNDS ZUI Style Sheet.asset";
        public const string SkinFolder = "Assets/Packages/Laubrary/Editor/Zounds/Uitk/Skin";

        public static readonly string[] ButtonStyles = { "RichButton", "RichToggle", "Default", "ZoundBtn", "ZoundBtnFlat", "ZoundBtnFlatToggle", "Flat", "MainTab" };
        public static readonly string[] SliderStyles = { "Default", "SmallSlider", "BigSlider", "MinMax", "MinMaxPitch", "Chance" };
        public static readonly string[] BoxStyles = { "Default", "Alternative", "Warning", "Subtle", "Info" };

        static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

        public static string Generate() {
            var sheet = AssetDatabase.LoadAssetAtPath<ZUIStyleSheetAsset>(SheetPath);
            if (sheet == null) return "Zounds style sheet not found at " + SheetPath;
            Directory.CreateDirectory(SkinFolder);
            var written = new List<string>();
            var css = new StringBuilder();
            css.Append("/* GENERATED by ZoundsSkinExtractor from the Zounds ZUI style sheet: a COPY of the old windows' look for the\n")
               .Append("   UI Toolkit port (owner's decision 2026-09-28). Do not edit by hand; regenerate if the old look changes. */\n\n");

            // Palette as variables.
            css.Append(".zs-root {\n");
            foreach (var p in sheet.palette) css.Append("    --zs-pal-").Append(Slug(p.name)).Append(": ").Append(Rgba(p.color)).Append(";\n");
            css.Append("}\n\n");

            foreach (var name in ButtonStyles) {
                var def = sheet.FindButton(name);
                if (def == null) continue;
                var (tl, tr, bl, br) = def.GetResolvedCornerFlags();
                int r = def.shape.fullyRound ? 999 : def.shape.cornerRadius;
                string cls = ".zs-" + name;
                // Base: reset Unity's own button look, then the normal state.
                css.Append(Sel(cls + ".unity-button, " + cls)).Append(" {\n")
                   .Append("    margin: 0; background-color: rgba(0,0,0,0);\n")
                   .Append("    -unity-background-scale-mode: stretch-to-fill;\n")
                   .Append("    padding-left: ").Append(def.padding.padH).Append("px; padding-right: ").Append(def.padding.padH).Append("px;\n")
                   .Append("    padding-top: 0; padding-bottom: 0;\n")
                   .Append("    -unity-text-align: middle-center;\n")
                   .Append(Corners(tl, tr, bl, br, r))
                   .Append("}\n");
                css.Append(State(cls + ".unity-button, " + cls, def, ZUIButtonDrawState.Normal, sheet, name, written));
                css.Append(State(cls + ".unity-button:hover, " + cls + ":hover", def, ZUIButtonDrawState.Hover, sheet, name, written));
                css.Append(State(cls + ".unity-button:active, " + cls + ":active", def, ZUIButtonDrawState.Active, sheet, name, written));
                // A latched toggle shows its on state whatever the pointer is doing.
                css.Append(State(cls + ".zui-togglebutton--on, " + cls + ".zui-togglebutton--on:hover, " + cls + ".zui-togglebutton--on:active", def, ZUIButtonDrawState.ToggleOn, sheet, name, written));
                // Corner masks (ZUICornerMask via ZuiCorners): each overrides the style's own corners, radius kept.
                foreach (var (mask, m) in new[] { ("all", (true, true, true, true)), ("left", (true, false, true, false)), ("right", (false, true, false, true)),
                                                  ("top", (true, true, false, false)), ("bottom", (false, false, true, true)), ("square", (false, false, false, false)) })
                    css.Append(Sel(cls + ".zui-corners--" + mask)).Append(" {\n").Append(Corners(m.Item1, m.Item2, m.Item3, m.Item4, r)).Append("}\n");
                css.Append('\n');
            }

            foreach (var name in SliderStyles) {
                var def = sheet.FindSlider(name);
                if (def == null) continue;
                string cls = ".zs-slider-" + Slug(name);
                css.Append(Box(cls + " .zui-skinslider__fill", def.trackFill, sheet, "slider-" + Slug(name) + "_fill", written));
                css.Append(Box(cls + " .zui-skinslider__rest", def.track, sheet, "slider-" + Slug(name) + "_track", written));
                css.Append(Sel(cls + " .zui-skinslider__label")).Append(" {\n").Append(Text(def.labelText, sheet)).Append("}\n");
                css.Append(Sel(cls + " .zui-skinminmax__field")).Append(" {\n").Append(Text(def.valueText, sheet)).Append("}\n");
                // Range edges (MicroMinMax): the style's thumb, thumbMax and thumbCenter, full track height, thumbWidth wide.
                // At 2 px or less the old ZUI draws them square (its rounded path would inset the fill to nothing).
                float w = Mathf.Max(0f, def.thumbWidth);
                foreach (var (part, t) in new[] { ("min", def.thumb), ("max", def.thumbMax ?? def.thumb), ("center", def.thumbCenter ?? def.thumb) }) {
                    if (t == null) continue;
                    string sel = cls + " .zui-skinminmax__edge--" + part;
                    string file = "slider-" + Slug(name) + "_edge-" + part;
                    int r = w <= 2f ? 0 : t.GetResolvedCornerRadius();
                    css.Append(Sel(sel)).Append(" {\n    width: ").Append(w.ToString("0.##", Inv)).Append("px;\n    -unity-background-scale-mode: stretch-to-fill;\n")
                       .Append("    border-radius: ").Append(r).Append("px;\n")
                       .Append(Fill(t.GetColor(ZUIButtonDrawState.Normal), sheet, file + "_Normal", written)).Append(Border(t.GetBorder(ZUIButtonDrawState.Normal), sheet)).Append("}\n");
                    css.Append(Sel(sel + ":hover")).Append(" {\n").Append(Fill(t.GetColor(ZUIButtonDrawState.Hover), sheet, file + "_Hover", written)).Append(Border(t.GetBorder(ZUIButtonDrawState.Hover), sheet)).Append("}\n");
                    css.Append(Sel(sel + ".zui-skinminmax__edge--active")).Append(" {\n").Append(Fill(t.GetColor(ZUIButtonDrawState.Active), sheet, file + "_Active", written)).Append(Border(t.GetBorder(ZUIButtonDrawState.Active), sheet)).Append("}\n");
                }
                css.Append('\n');
            }

            // Named text styles (Title, Header, "Zounds Tags", ...), for labels the old windows draw with them.
            foreach (var ts in sheet.textStyles) {
                if (ts == null || string.IsNullOrEmpty(ts.name)) continue;
                css.Append(Sel(".zs-text-" + Slug(ts.name))).Append(" {\n").Append(Text(ts.text, sheet)).Append("}\n");
            }
            css.Append('\n');

            foreach (var name in BoxStyles) {
                var def = sheet.FindBox(name);
                if (def == null) continue;
                css.Append(Box(".zs-box-" + Slug(name), def, sheet, "box-" + Slug(name), written));
            }

            string ussPath = SkinFolder + "/ZoundsSkin.uss";
            File.WriteAllText(ussPath, css.ToString());
            AssetDatabase.Refresh();
            foreach (var png in written) ConfigureTexture(png);
            AssetDatabase.Refresh();
            return "wrote " + ussPath + " and " + written.Count + " textures";
        }

        /// <summary>Every rule descends from the window's .zs-root, one class more specific than ZUI's own control
        /// styling, so the copied look always wins over the stock ZUI Toolkit look it is layered on.</summary>
        static string Sel(string selector) {
            var parts = selector.Split(',');
            for (int i = 0; i < parts.Length; i++) parts[i] = ".zs-root " + parts[i].Trim();
            return string.Join(", ", parts);
        }

        static string State(string selector, ZUIButtonDef def, ZUIButtonDrawState st, ZUIStyleSheetAsset sheet, string name, List<string> written) {
            var sb = new StringBuilder(Sel(selector)).Append(" {\n");
            var col = def.GetColor(st);
            sb.Append(Fill(col, sheet, name + "_" + st, written));
            var txt = def.GetText(st);
            sb.Append(Text(txt, sheet));
            sb.Append(Border(def.GetBorder(st), sheet));
            sb.Append("}\n");
            return sb.ToString();
        }

        static string Box(string selector, ZUIBoxDef def, ZUIStyleSheetAsset sheet, string file, List<string> written) {
            if (def == null) return "";
            def.ownerSheet = sheet;
            var sb = new StringBuilder(Sel(selector)).Append(" {\n");
            sb.Append("    -unity-background-scale-mode: stretch-to-fill;\n");
            sb.Append(Fill(def.GetResolvedBackground(), sheet, file, written));
            sb.Append(Border(def.GetResolvedBorder(), sheet));
            var v = def.GetCornerVector(def.shape.fullyRound ? 999 : def.shape.cornerRadius);   // x TL, y TR, z BR, w BL
            sb.Append("    border-top-left-radius: ").Append(Px(v.x)).Append("; border-top-right-radius: ").Append(Px(v.y))
              .Append("; border-bottom-right-radius: ").Append(Px(v.z)).Append("; border-bottom-left-radius: ").Append(Px(v.w)).Append(";\n");
            // The box's own layout, as ZUI.Box lays it out (ZUIBoxDef.GetLayoutStyle): padding inside the background,
            // margin outside it. Only meaningful for a box used as a container (.zs-box-*), harmless on a track part.
            if (selector.StartsWith(".zs-box-")) {
                var lay = def.GetLayoutStyle();
                // IMGUI measures a box's padding from its outer edge (the border is drawn inside it); UI Toolkit puts
                // padding inside the border. So the border's width comes off each side's padding.
                var bdr = def.GetResolvedBorder();
                bool hasBorder = bdr != null && bdr.color.GetColorA(sheet).a > 0f;
                float bt = hasBorder ? bdr.edgeWidth.Top : 0f, br2 = hasBorder ? bdr.edgeWidth.Right : 0f, bb = hasBorder ? bdr.edgeWidth.Bottom : 0f, bl = hasBorder ? bdr.edgeWidth.Left : 0f;
                sb.Append("    padding: ").Append(Px2(lay.padding.top - bt)).Append(' ').Append(Px2(lay.padding.right - br2)).Append(' ')
                  .Append(Px2(lay.padding.bottom - bb)).Append(' ').Append(Px2(lay.padding.left - bl)).Append(";\n");
                sb.Append("    margin: ").Append(lay.margin.top).Append("px ").Append(lay.margin.right).Append("px ").Append(lay.margin.bottom).Append("px ").Append(lay.margin.left).Append("px;\n");
            }
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>A flat fill becomes a colour; a gradient becomes the very texture the old ZUI draws with.</summary>
        static string Fill(ZUIColor col, ZUIStyleSheetAsset sheet, string file, List<string> written) {
            if (col == null) return "    background-image: none;\n";
            if (!col.isGradient && !col.isRadial) return "    background-image: none;\n    background-color: " + Rgba(col.GetColorA(sheet)) + ";\n";
            if (col.usePixelLength && col.pixelLength > 0 && col.pixelEdges != ZUIPixelEdges.None) return PixelEdgeFill(col, sheet, file, written);
            var tex = col.GetOrBuildTexture(sheet);
            if (tex == null) return "    background-image: none;\n    background-color: " + Rgba(col.GetColorA(sheet)) + ";\n";
            string png = SkinFolder + "/" + file + ".png";
            File.WriteAllBytes(png, Readable(tex).EncodeToPNG());
            written.Add(png);
            return "    background-color: rgba(0,0,0,0);\n    background-image: url(\"" + file + ".png\");\n";
        }

        /// <summary>
        /// A "pixel-length" gradient (e.g. the Zounds Default box): the second colour everywhere, with a gradient band
        /// exactly pixelLength wide along each chosen edge (first colour at the edge), and where two chosen edges meet
        /// the minimum of both — ZUIColor.DrawPixelMultiEdge's arithmetic, pixel for pixel. Baked as a small texture that
        /// USS 9-slices by pixelLength on every side, so the bands keep their width at any box size.
        /// </summary>
        static string PixelEdgeFill(ZUIColor col, ZUIStyleSheetAsset sheet, string file, List<string> written) {
            int L = col.pixelLength, W = 2 * L + 2, H = W;
            var edges = col.pixelEdges;
            bool hasL = (edges & ZUIPixelEdges.Left) != 0, hasR = (edges & ZUIPixelEdges.Right) != 0;
            bool hasT = (edges & ZUIPixelEdges.Top) != 0, hasB = (edges & ZUIPixelEdges.Bottom) != 0;
            var sample = typeof(ZUIColor).GetMethod("SampleColor", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Public);
            Color S(float t) => (Color)sample.Invoke(col, new object[] { t, sheet });
            float m = Mathf.Max(L - 1, 1);
            var tex = new Texture2D(W, H, TextureFormat.RGBA32, false);
            for (int y = 0; y < H; y++)
                for (int x = 0; x < W; x++) {
                    // Texture rows run bottom-up.
                    bool inL = hasL && x < L, inR = hasR && x >= W - L, inB = hasB && y < L, inT = hasT && y >= H - L;
                    float th = inL ? x / m : inR ? (W - 1 - x) / m : float.MaxValue;
                    float tv = inB ? y / m : inT ? (H - 1 - y) / m : float.MaxValue;
                    float t = Mathf.Min(th, tv);
                    tex.SetPixel(x, y, t == float.MaxValue ? col.GetColorB(sheet) : S(t));
                }
            tex.Apply();
            string png = SkinFolder + "/" + file + ".png";
            File.WriteAllBytes(png, tex.EncodeToPNG());
            written.Add(png);
            return "    background-color: rgba(0,0,0,0);\n    background-image: url(\"" + file + ".png\");\n"
                 + "    -unity-slice-left: " + L + "; -unity-slice-right: " + L + "; -unity-slice-top: " + L + "; -unity-slice-bottom: " + L + ";\n";
        }

        static string Text(ZUITextDef t, ZUIStyleSheetAsset sheet) {
            if (t == null) return "";
            var sb = new StringBuilder();
            sb.Append("    color: ").Append(Rgba(t.color.Resolve(sheet))).Append(";\n");
            if (t.fontSize > 0) sb.Append("    font-size: ").Append(t.fontSize).Append("px;\n");
            sb.Append("    -unity-font-style: ").Append(t.fontStyle == FontStyle.Bold ? "bold" : t.fontStyle == FontStyle.Italic ? "italic" : t.fontStyle == FontStyle.BoldAndItalic ? "bold-and-italic" : "normal").Append(";\n");
            // A text shadow is a hard, offset copy of the text in the old ZUI; USS draws the same thing natively. Written
            // explicitly as none when off, because states override each other (a style's hover may add one normal lacks).
            if (t.shadowEnabled)
                sb.Append("    text-shadow: ").Append(t.shadowOffset.x.ToString("0.##", Inv)).Append("px ").Append(t.shadowOffset.y.ToString("0.##", Inv))
                  .Append("px 0px ").Append(Rgba(t.shadowColor.Resolve(sheet))).Append(";\n");
            else sb.Append("    text-shadow: 0px 0px 0px rgba(0,0,0,0);\n");
            if (t.outlineEnabled)
                sb.Append("    -unity-text-outline-width: ").Append(t.outlineWidth).Append("px;\n    -unity-text-outline-color: ").Append(Rgba(t.outlineColor.Resolve(sheet))).Append(";\n");
            return sb.ToString();
        }

        static string Border(ZUIBorderDef b, ZUIStyleSheetAsset sheet) {
            if (b == null) return "    border-width: 0;\n";
            var e = b.edgeWidth;
            var c = b.color.GetColorA(sheet);
            if (c.a <= 0f) return "    border-width: 0;\n";
            return "    border-top-width: " + Px(e.Top) + "; border-right-width: " + Px(e.Right) + "; border-bottom-width: " + Px(e.Bottom) + "; border-left-width: " + Px(e.Left) + ";\n"
                 + "    border-color: " + Rgba(c) + ";\n";
        }

        static string Corners(bool tl, bool tr, bool bl, bool br, int r) =>
            "    border-top-left-radius: " + (tl ? r : 0) + "px; border-top-right-radius: " + (tr ? r : 0) + "px; border-bottom-left-radius: " + (bl ? r : 0) + "px; border-bottom-right-radius: " + (br ? r : 0) + "px;\n";

        static Texture2D Readable(Texture2D tex) {
            var rt = RenderTexture.GetTemporary(tex.width, tex.height, 0, RenderTextureFormat.ARGB32, RenderTextureReadWrite.sRGB);
            Graphics.Blit(tex, rt);
            var prev = RenderTexture.active; RenderTexture.active = rt;
            var copy = new Texture2D(tex.width, tex.height, TextureFormat.RGBA32, false);
            copy.ReadPixels(new Rect(0, 0, tex.width, tex.height), 0, 0); copy.Apply();
            RenderTexture.active = prev; RenderTexture.ReleaseTemporary(rt);
            return copy;
        }

        static void ConfigureTexture(string path) {
            var imp = AssetImporter.GetAtPath(path) as TextureImporter;
            if (imp == null) return;
            imp.textureType = TextureImporterType.Default;
            imp.mipmapEnabled = false;
            imp.wrapMode = TextureWrapMode.Clamp;
            imp.filterMode = FilterMode.Bilinear;
            imp.textureCompression = TextureImporterCompression.Uncompressed;
            imp.npotScale = TextureImporterNPOTScale.None;
            imp.alphaIsTransparency = true;
            imp.SaveAndReimport();
        }

        static string Px(float v) => Mathf.RoundToInt(v).ToString(Inv) + "px";
        static string Px2(float v) => Mathf.Max(0f, v).ToString("0.##", Inv) + "px";

        static string Rgba(Color c) =>
            "rgba(" + Mathf.RoundToInt(c.r * 255f) + "," + Mathf.RoundToInt(c.g * 255f) + "," + Mathf.RoundToInt(c.b * 255f) + "," + c.a.ToString("0.###", Inv) + ")";

        static string Slug(string s) {
            var sb = new StringBuilder();
            foreach (char ch in s.ToLowerInvariant()) sb.Append(char.IsLetterOrDigit(ch) ? ch : '-');
            return sb.ToString();
        }
    }
}
