var sb = new System.Text.StringBuilder();
var s = new Laubrary.Shaper.ShaperCherryFrame { sourceIndex = 3 };
sb.Append("Variable length OFF:\n");
s.useMinMaxLength = false;
s.lengthMultiplier = 1f; s.minLengthMultiplier = 1f; s.maxLengthMultiplier = 1f;
sb.Append("  base                 -> ").Append(s.ResolveLength(0,0,0)).Append('\n');
s.minLengthMultiplier = 0.25f; s.maxLengthMultiplier = 8f;
sb.Append("  Min 0.25 / Max 8     -> ").Append(s.ResolveLength(0,0,0)).Append("   (Min/Max DEAD)\n");
s.lengthMultiplier = 4f;
sb.Append("  Length x 4           -> ").Append(s.ResolveLength(0,0,0)).Append("   (Length LIVE)\n");
sb.Append("Variable length ON:\n");
s.useMinMaxLength = true;
s.lengthMultiplier = 1f; s.minLengthMultiplier = 2f; s.maxLengthMultiplier = 2f;
sb.Append("  Min=Max=2, Length 1  -> ").Append(s.ResolveLength(0,0,0)).Append('\n');
s.lengthMultiplier = 7f;
sb.Append("  Min=Max=2, Length 7  -> ").Append(s.ResolveLength(0,0,0)).Append("   (Length DEAD)\n");
s.minLengthMultiplier = 0.25f; s.maxLengthMultiplier = 8f;
sb.Append("  Min 0.25 / Max 8     -> ").Append(s.ResolveLength(0,0,0)).Append(" / ").Append(s.ResolveLength(0,0,1)).Append(" / ").Append(s.ResolveLength(0,0,2)).Append("   (Min/Max LIVE)\n");
return sb.ToString();
